// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: wandb/proto/wandb_filestream_v1.proto

package filestreamv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Kind is the type tag of one cell. It selects the payload array.
type MetricsBatch_Kind int32

const (
	MetricsBatch_KIND_NULL   MetricsBatch_Kind = 0
	MetricsBatch_KIND_FLOAT  MetricsBatch_Kind = 1
	MetricsBatch_KIND_INT    MetricsBatch_Kind = 2
	MetricsBatch_KIND_BOOL   MetricsBatch_Kind = 3
	MetricsBatch_KIND_STRING MetricsBatch_Kind = 4
	// Anything not representable in the other five kinds, kept as JSON text.
	// Nested values are represented as `KIND_JSON` cells under their
	// top-level key.
	MetricsBatch_KIND_JSON MetricsBatch_Kind = 5
)

// Enum value maps for MetricsBatch_Kind.
var (
	MetricsBatch_Kind_name = map[int32]string{
		0: "KIND_NULL",
		1: "KIND_FLOAT",
		2: "KIND_INT",
		3: "KIND_BOOL",
		4: "KIND_STRING",
		5: "KIND_JSON",
	}
	MetricsBatch_Kind_value = map[string]int32{
		"KIND_NULL":   0,
		"KIND_FLOAT":  1,
		"KIND_INT":    2,
		"KIND_BOOL":   3,
		"KIND_STRING": 4,
		"KIND_JSON":   5,
	}
)

func (x MetricsBatch_Kind) Enum() *MetricsBatch_Kind {
	p := new(MetricsBatch_Kind)
	*p = x
	return p
}

func (x MetricsBatch_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetricsBatch_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_wandb_proto_wandb_filestream_v1_proto_enumTypes[0].Descriptor()
}

func (MetricsBatch_Kind) Type() protoreflect.EnumType {
	return &file_wandb_proto_wandb_filestream_v1_proto_enumTypes[0]
}

func (x MetricsBatch_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetricsBatch_Kind.Descriptor instead.
func (MetricsBatch_Kind) EnumDescriptor() ([]byte, []int) {
	return file_wandb_proto_wandb_filestream_v1_proto_rawDescGZIP(), []int{3, 0}
}

// FileStreamUpload is data that can be sent via filestream.
type FileStreamUpload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Line-oriented file updates: history, events, and console output.
	// This is the legacy format.
	Files []*FileStreamChunk `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	// Typed history rows. Replaces the "wandb-history.jsonl" entry in `files`.
	History *MetricsBatchChunk `protobuf:"bytes,2,opt,name=history,proto3" json:"history,omitempty"`
	// Names of files that finished uploading.
	Uploaded []string `protobuf:"bytes,3,rep,name=uploaded,proto3" json:"uploaded,omitempty"`
	// The run is about to be preempted. It will not send heartbeats for
	// a while, but it may resume later.
	Preempting *bool `protobuf:"varint,4,opt,name=preempting,proto3,oneof" json:"preempting,omitempty"`
	// The run finished.
	Complete *bool `protobuf:"varint,5,opt,name=complete,proto3,oneof" json:"complete,omitempty"`
	// The exit code of the run's source script. Only meaningful when `complete` is set.
	Exitcode      *int32 `protobuf:"varint,6,opt,name=exitcode,proto3,oneof" json:"exitcode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileStreamUpload) Reset() {
	*x = FileStreamUpload{}
	mi := &file_wandb_proto_wandb_filestream_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileStreamUpload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileStreamUpload) ProtoMessage() {}

func (x *FileStreamUpload) ProtoReflect() protoreflect.Message {
	mi := &file_wandb_proto_wandb_filestream_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileStreamUpload.ProtoReflect.Descriptor instead.
func (*FileStreamUpload) Descriptor() ([]byte, []int) {
	return file_wandb_proto_wandb_filestream_v1_proto_rawDescGZIP(), []int{0}
}

func (x *FileStreamUpload) GetFiles() []*FileStreamChunk {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *FileStreamUpload) GetHistory() *MetricsBatchChunk {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *FileStreamUpload) GetUploaded() []string {
	if x != nil {
		return x.Uploaded
	}
	return nil
}

func (x *FileStreamUpload) GetPreempting() bool {
	if x != nil && x.Preempting != nil {
		return *x.Preempting
	}
	return false
}

func (x *FileStreamUpload) GetComplete() bool {
	if x != nil && x.Complete != nil {
		return *x.Complete
	}
	return false
}

func (x *FileStreamUpload) GetExitcode() int32 {
	if x != nil && x.Exitcode != nil {
		return *x.Exitcode
	}
	return 0
}

// FileStreamChunk appends or overwrites lines in one filestream file.
type FileStreamChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The filestream file name, for example "wandb-events.jsonl".
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The line number of the first line in `content`.
	Offset int64 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	// The lines to write, in order.
	Content       []string `protobuf:"bytes,3,rep,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileStreamChunk) Reset() {
	*x = FileStreamChunk{}
	mi := &file_wandb_proto_wandb_filestream_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileStreamChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileStreamChunk) ProtoMessage() {}

func (x *FileStreamChunk) ProtoReflect() protoreflect.Message {
	mi := &file_wandb_proto_wandb_filestream_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileStreamChunk.ProtoReflect.Descriptor instead.
func (*FileStreamChunk) Descriptor() ([]byte, []int) {
	return file_wandb_proto_wandb_filestream_v1_proto_rawDescGZIP(), []int{1}
}

func (x *FileStreamChunk) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileStreamChunk) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *FileStreamChunk) GetContent() []string {
	if x != nil {
		return x.Content
	}
	return nil
}

// MetricsBatchChunk appends typed history rows at a stream row offset.
//
// Row offset is the same as the legacy "line" offset.
type MetricsBatchChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The history line number of the first row in `batch`.
	Offset int64 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	// The count of rows in the batch. Used to validate the batch.
	RowCount int64 `protobuf:"varint,2,opt,name=row_count,json=rowCount,proto3" json:"row_count,omitempty"`
	// The batch of rows.
	Batch         *MetricsBatch `protobuf:"bytes,3,opt,name=batch,proto3" json:"batch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsBatchChunk) Reset() {
	*x = MetricsBatchChunk{}
	mi := &file_wandb_proto_wandb_filestream_v1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsBatchChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsBatchChunk) ProtoMessage() {}

func (x *MetricsBatchChunk) ProtoReflect() protoreflect.Message {
	mi := &file_wandb_proto_wandb_filestream_v1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsBatchChunk.ProtoReflect.Descriptor instead.
func (*MetricsBatchChunk) Descriptor() ([]byte, []int) {
	return file_wandb_proto_wandb_filestream_v1_proto_rawDescGZIP(), []int{2}
}

func (x *MetricsBatchChunk) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *MetricsBatchChunk) GetRowCount() int64 {
	if x != nil {
		return x.RowCount
	}
	return 0
}

func (x *MetricsBatchChunk) GetBatch() *MetricsBatch {
	if x != nil {
		return x.Batch
	}
	return nil
}

// MetricsBatch is a columnar set of metric rows.
//
// Keys are dictionary-encoded once per batch. Cells are stored in row
// order as (key id, kind) coordinates, and payloads are packed into one
// array per kind. One metric, named by `seq_key`, is a dense per-row
// column instead of a cell. For history, it is `_step`.
//
// Example:
//
//	rows:
//	  {"_step": 0, "loss": 0.5}
//	  {"_step": 1, "loss": NaN, "note": "spike"}
//	  {"_step": 2, "big": 9007199254740993}
//
//	batch:
//	  keys:       ["loss", "note", "big"]
//	  row_ends:   [1, 3, 4]
//	  cell_keys:  [0, 0, 1, 2]
//	  cell_kinds: [FLOAT, FLOAT, STRING, INT]
//	  floats:     [0.5, NaN]
//	  ints:       [9007199254740993]
//	  strings:    ["spike"]
//	  seqs:       [0, 1, 2]
//	  has_seq:    [1, 1, 1]
//	  seq_key:    ""            (empty means "_step")
//
// This layout is very similar to the server's internal batch, but the two
// schemas are independent and evolve separately.
//
// A decoder must reject a batch when any of these conditions is false:
//   - `row_ends` is non-decreasing, and its last entry equals the cell count.
//   - `cell_keys` has one entry per cell, and every entry indexes into `keys`.
//   - `cell_kinds` has one entry per cell, and every entry is a known Kind.
//   - Each payload array has exactly as many entries as there are cells
//     of its kind.
//   - `keys` are unique and non-empty, and no row repeats a key.
//   - `seqs` and `has_seq` are both empty, or both have one entry per row.
//   - `seq_key` is empty or a key the route supports.
//
// The cell count is the length of `cell_kinds`.
type MetricsBatch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The key dictionary. `cell_keys` index into it.
	//
	// Keys are top-level metric names. A nested value is one `KIND_JSON` cell
	// under its top-level key. The sequence key (`seq_key`) is not in `keys`.
	// It has its own column, `seqs`.
	Keys []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	// row_ends[i] is the cumulative cell count through row i, so row i
	// spans cells [row_ends[i-1], row_ends[i]). The row count is the
	// length of this array. A row may have zero cells.
	RowEnds []uint32 `protobuf:"varint,2,rep,packed,name=row_ends,json=rowEnds,proto3" json:"row_ends,omitempty"`
	// The key id of each cell, in row order.
	CellKeys []uint32 `protobuf:"varint,3,rep,packed,name=cell_keys,json=cellKeys,proto3" json:"cell_keys,omitempty"`
	// The Kind of each cell, in row order. One byte per cell.
	CellKinds []byte `protobuf:"bytes,4,opt,name=cell_kinds,json=cellKinds,proto3" json:"cell_kinds,omitempty"`
	// Payload arrays. The cells of one kind take payloads from that kind's
	// array in cell order. A KIND_NULL cell has no payload.
	Floats  []float64 `protobuf:"fixed64,5,rep,packed,name=floats,proto3" json:"floats,omitempty"`
	Ints    []int64   `protobuf:"zigzag64,6,rep,packed,name=ints,proto3" json:"ints,omitempty"`
	Bools   []bool    `protobuf:"varint,7,rep,packed,name=bools,proto3" json:"bools,omitempty"`
	Strings []string  `protobuf:"bytes,8,rep,name=strings,proto3" json:"strings,omitempty"`
	Jsons   []string  `protobuf:"bytes,9,rep,name=jsons,proto3" json:"jsons,omitempty"`
	// Dense column of sequence values, one entry per row.
	Seqs []int64 `protobuf:"zigzag64,10,rep,packed,name=seqs,proto3" json:"seqs,omitempty"`
	// Presence of seq values, one byte per row (0 = not present, 1 = present).
	HasSeq []byte `protobuf:"bytes,11,opt,name=has_seq,json=hasSeq,proto3" json:"has_seq,omitempty"`
	// The metric key for the `seqs` column: `"_step"` for history,
	// `"_timestamp"` for events, `"_offset"` for logs. Must be non-empty.
	SeqKey        string `protobuf:"bytes,12,opt,name=seq_key,json=seqKey,proto3" json:"seq_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsBatch) Reset() {
	*x = MetricsBatch{}
	mi := &file_wandb_proto_wandb_filestream_v1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsBatch) ProtoMessage() {}

func (x *MetricsBatch) ProtoReflect() protoreflect.Message {
	mi := &file_wandb_proto_wandb_filestream_v1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsBatch.ProtoReflect.Descriptor instead.
func (*MetricsBatch) Descriptor() ([]byte, []int) {
	return file_wandb_proto_wandb_filestream_v1_proto_rawDescGZIP(), []int{3}
}

func (x *MetricsBatch) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *MetricsBatch) GetRowEnds() []uint32 {
	if x != nil {
		return x.RowEnds
	}
	return nil
}

func (x *MetricsBatch) GetCellKeys() []uint32 {
	if x != nil {
		return x.CellKeys
	}
	return nil
}

func (x *MetricsBatch) GetCellKinds() []byte {
	if x != nil {
		return x.CellKinds
	}
	return nil
}

func (x *MetricsBatch) GetFloats() []float64 {
	if x != nil {
		return x.Floats
	}
	return nil
}

func (x *MetricsBatch) GetInts() []int64 {
	if x != nil {
		return x.Ints
	}
	return nil
}

func (x *MetricsBatch) GetBools() []bool {
	if x != nil {
		return x.Bools
	}
	return nil
}

func (x *MetricsBatch) GetStrings() []string {
	if x != nil {
		return x.Strings
	}
	return nil
}

func (x *MetricsBatch) GetJsons() []string {
	if x != nil {
		return x.Jsons
	}
	return nil
}

func (x *MetricsBatch) GetSeqs() []int64 {
	if x != nil {
		return x.Seqs
	}
	return nil
}

func (x *MetricsBatch) GetHasSeq() []byte {
	if x != nil {
		return x.HasSeq
	}
	return nil
}

func (x *MetricsBatch) GetSeqKey() string {
	if x != nil {
		return x.SeqKey
	}
	return ""
}

var File_wandb_proto_wandb_filestream_v1_proto protoreflect.FileDescriptor

const file_wandb_proto_wandb_filestream_v1_proto_rawDesc = "" +
	"\n" +
	"%wandb/proto/wandb_filestream_v1.proto\x12\x13wandb.filestream.v1\"\xbc\x02\n" +
	"\x10FileStreamUpload\x12:\n" +
	"\x05files\x18\x01 \x03(\v2$.wandb.filestream.v1.FileStreamChunkR\x05files\x12@\n" +
	"\ahistory\x18\x02 \x01(\v2&.wandb.filestream.v1.MetricsBatchChunkR\ahistory\x12\x1a\n" +
	"\buploaded\x18\x03 \x03(\tR\buploaded\x12#\n" +
	"\n" +
	"preempting\x18\x04 \x01(\bH\x00R\n" +
	"preempting\x88\x01\x01\x12\x1f\n" +
	"\bcomplete\x18\x05 \x01(\bH\x01R\bcomplete\x88\x01\x01\x12\x1f\n" +
	"\bexitcode\x18\x06 \x01(\x05H\x02R\bexitcode\x88\x01\x01B\r\n" +
	"\v_preemptingB\v\n" +
	"\t_completeB\v\n" +
	"\t_exitcode\"W\n" +
	"\x0fFileStreamChunk\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x18\n" +
	"\acontent\x18\x03 \x03(\tR\acontent\"\x81\x01\n" +
	"\x11MetricsBatchChunk\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x03R\x06offset\x12\x1b\n" +
	"\trow_count\x18\x02 \x01(\x03R\browCount\x127\n" +
	"\x05batch\x18\x03 \x01(\v2!.wandb.filestream.v1.MetricsBatchR\x05batch\"\x95\x03\n" +
	"\fMetricsBatch\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\tR\x04keys\x12\x19\n" +
	"\brow_ends\x18\x02 \x03(\rR\arowEnds\x12\x1b\n" +
	"\tcell_keys\x18\x03 \x03(\rR\bcellKeys\x12\x1d\n" +
	"\n" +
	"cell_kinds\x18\x04 \x01(\fR\tcellKinds\x12\x16\n" +
	"\x06floats\x18\x05 \x03(\x01R\x06floats\x12\x12\n" +
	"\x04ints\x18\x06 \x03(\x12R\x04ints\x12\x14\n" +
	"\x05bools\x18\a \x03(\bR\x05bools\x12\x18\n" +
	"\astrings\x18\b \x03(\tR\astrings\x12\x14\n" +
	"\x05jsons\x18\t \x03(\tR\x05jsons\x12\x12\n" +
	"\x04seqs\x18\n" +
	" \x03(\x12R\x04seqs\x12\x17\n" +
	"\ahas_seq\x18\v \x01(\fR\x06hasSeq\x12\x17\n" +
	"\aseq_key\x18\f \x01(\tR\x06seqKey\"b\n" +
	"\x04Kind\x12\r\n" +
	"\tKIND_NULL\x10\x00\x12\x0e\n" +
	"\n" +
	"KIND_FLOAT\x10\x01\x12\f\n" +
	"\bKIND_INT\x10\x02\x12\r\n" +
	"\tKIND_BOOL\x10\x03\x12\x0f\n" +
	"\vKIND_STRING\x10\x04\x12\r\n" +
	"\tKIND_JSON\x10\x05B+Z)core/pkg/filestream_proto/v1;filestreamv1b\x06proto3"

var (
	file_wandb_proto_wandb_filestream_v1_proto_rawDescOnce sync.Once
	file_wandb_proto_wandb_filestream_v1_proto_rawDescData []byte
)

func file_wandb_proto_wandb_filestream_v1_proto_rawDescGZIP() []byte {
	file_wandb_proto_wandb_filestream_v1_proto_rawDescOnce.Do(func() {
		file_wandb_proto_wandb_filestream_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wandb_proto_wandb_filestream_v1_proto_rawDesc), len(file_wandb_proto_wandb_filestream_v1_proto_rawDesc)))
	})
	return file_wandb_proto_wandb_filestream_v1_proto_rawDescData
}

var file_wandb_proto_wandb_filestream_v1_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_wandb_proto_wandb_filestream_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_wandb_proto_wandb_filestream_v1_proto_goTypes = []any{
	(MetricsBatch_Kind)(0),    // 0: wandb.filestream.v1.MetricsBatch.Kind
	(*FileStreamUpload)(nil),  // 1: wandb.filestream.v1.FileStreamUpload
	(*FileStreamChunk)(nil),   // 2: wandb.filestream.v1.FileStreamChunk
	(*MetricsBatchChunk)(nil), // 3: wandb.filestream.v1.MetricsBatchChunk
	(*MetricsBatch)(nil),      // 4: wandb.filestream.v1.MetricsBatch
}
var file_wandb_proto_wandb_filestream_v1_proto_depIdxs = []int32{
	2, // 0: wandb.filestream.v1.FileStreamUpload.files:type_name -> wandb.filestream.v1.FileStreamChunk
	3, // 1: wandb.filestream.v1.FileStreamUpload.history:type_name -> wandb.filestream.v1.MetricsBatchChunk
	4, // 2: wandb.filestream.v1.MetricsBatchChunk.batch:type_name -> wandb.filestream.v1.MetricsBatch
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_wandb_proto_wandb_filestream_v1_proto_init() }
func file_wandb_proto_wandb_filestream_v1_proto_init() {
	if File_wandb_proto_wandb_filestream_v1_proto != nil {
		return
	}
	file_wandb_proto_wandb_filestream_v1_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wandb_proto_wandb_filestream_v1_proto_rawDesc), len(file_wandb_proto_wandb_filestream_v1_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wandb_proto_wandb_filestream_v1_proto_goTypes,
		DependencyIndexes: file_wandb_proto_wandb_filestream_v1_proto_depIdxs,
		EnumInfos:         file_wandb_proto_wandb_filestream_v1_proto_enumTypes,
		MessageInfos:      file_wandb_proto_wandb_filestream_v1_proto_msgTypes,
	}.Build()
	File_wandb_proto_wandb_filestream_v1_proto = out.File
	file_wandb_proto_wandb_filestream_v1_proto_goTypes = nil
	file_wandb_proto_wandb_filestream_v1_proto_depIdxs = nil
}
