// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package runsync

import (
	"github.com/google/wire"
	"github.com/wandb/wandb/core/internal/api"
	"github.com/wandb/wandb/core/internal/featurechecker"
	"github.com/wandb/wandb/core/internal/filestream"
	"github.com/wandb/wandb/core/internal/filetransfer"
	"github.com/wandb/wandb/core/internal/mailbox"
	"github.com/wandb/wandb/core/internal/observability"
	"github.com/wandb/wandb/core/internal/runfiles"
	"github.com/wandb/wandb/core/internal/runhandle"
	"github.com/wandb/wandb/core/internal/settings"
	"github.com/wandb/wandb/core/internal/sharedmode"
	"github.com/wandb/wandb/core/internal/stream"
	"github.com/wandb/wandb/core/internal/tensorboard"
	"github.com/wandb/wandb/core/internal/watcher"
	"github.com/wandb/wandb/core/internal/wboperation"
)

// Injectors from wire.go:

func InjectRunSyncerFactory(settings2 *settings.Settings, logger *observability.CoreLogger) *RunSyncerFactory {
	wandbOperations := wboperation.NewOperations()
	printer := observability.NewPrinter()
	wbBaseURL := stream.BaseURLFromSettings(logger, settings2)
	clientID := sharedmode.RandomClientID()
	credentialProvider := stream.CredentialsFromSettings(logger, settings2)
	peeker := &observability.Peeker{}
	client := stream.NewGraphQLClient(wbBaseURL, clientID, credentialProvider, logger, peeker, settings2)
	serverFeaturesCache := featurechecker.NewServerFeaturesCache(client, logger)
	runHandle := runhandle.New()
	recordParserFactory := &stream.RecordParserFactory{
		FeatureProvider:    serverFeaturesCache,
		GraphqlClientOrNil: client,
		Logger:             logger,
		Operations:         wandbOperations,
		RunHandle:          runHandle,
		ClientID:           clientID,
		Settings:           settings2,
	}
	runReaderFactory := &RunReaderFactory{
		Logger:     logger,
		Operations: wandbOperations,
	}
	fileStreamFactory := &filestream.FileStreamFactory{
		BaseURL:    wbBaseURL,
		Logger:     logger,
		Operations: wandbOperations,
		Printer:    printer,
		Settings:   settings2,
	}
	fileTransferStats := filetransfer.NewFileTransferStats()
	fileTransferManager := stream.NewFileTransferManager(wbBaseURL, fileTransferStats, logger, settings2)
	watcher := provideFileWatcher(logger)
	uploaderFactory := &runfiles.UploaderFactory{
		FileTransfer: fileTransferManager,
		FileWatcher:  watcher,
		GraphQL:      client,
		Logger:       logger,
		Operations:   wandbOperations,
		RunHandle:    runHandle,
		Settings:     settings2,
	}
	mailboxMailbox := mailbox.New()
	senderFactory := &stream.SenderFactory{
		BaseURL:                 wbBaseURL,
		ClientID:                clientID,
		CredentialProvider:      credentialProvider,
		Logger:                  logger,
		Operations:              wandbOperations,
		Settings:                settings2,
		FeatureProvider:         serverFeaturesCache,
		FileStreamFactory:       fileStreamFactory,
		FileTransferManager:     fileTransferManager,
		FileTransferStats:       fileTransferStats,
		FileWatcher:             watcher,
		RunfilesUploaderFactory: uploaderFactory,
		GraphqlClient:           client,
		Peeker:                  peeker,
		RunHandle:               runHandle,
		Mailbox:                 mailboxMailbox,
	}
	tbHandlerFactory := &tensorboard.TBHandlerFactory{
		Logger:   logger,
		Settings: settings2,
	}
	runSyncerFactory := &RunSyncerFactory{
		Logger:              logger,
		Operations:          wandbOperations,
		Printer:             printer,
		RecordParserFactory: recordParserFactory,
		RunHandle:           runHandle,
		RunReaderFactory:    runReaderFactory,
		SenderFactory:       senderFactory,
		Settings:            settings2,
		TBHandlerFactory:    tbHandlerFactory,
	}
	return runSyncerFactory
}

// wire.go:

var runSyncerFactoryBindings = wire.NewSet(wire.Bind(new(api.Peeker), new(*observability.Peeker)), wire.Struct(new(observability.Peeker)), featurechecker.NewServerFeaturesCache, filestream.FileStreamProviders, filetransfer.NewFileTransferStats, mailbox.New, observability.NewPrinter, provideFileWatcher, runfiles.UploaderProviders, runhandle.New, runReaderProviders,
	runSyncerProviders, sharedmode.RandomClientID, stream.BaseURLFromSettings, stream.CredentialsFromSettings, stream.NewFileTransferManager, stream.NewGraphQLClient, stream.RecordParserProviders, stream.SenderProviders, tensorboard.TBHandlerProviders, wboperation.NewOperations,
)

func provideFileWatcher(logger *observability.CoreLogger) watcher.Watcher {
	return watcher.New(watcher.Params{Logger: logger})
}
