from google.protobuf import wrappers_pb2 as _wrappers_pb2
from google.protobuf.internal import containers as _containers
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from typing import ClassVar as _ClassVar, Iterable as _Iterable, Mapping as _Mapping, Optional as _Optional, Union as _Union

DESCRIPTOR: _descriptor.FileDescriptor

class ListStringValue(_message.Message):
    __slots__ = ["value"]
    VALUE_FIELD_NUMBER: _ClassVar[int]
    value: _containers.RepeatedScalarFieldContainer[str]
    def __init__(self, value: _Optional[_Iterable[str]] = ...) -> None: ...

class ListIntValue(_message.Message):
    __slots__ = ["value"]
    VALUE_FIELD_NUMBER: _ClassVar[int]
    value: _containers.RepeatedScalarFieldContainer[int]
    def __init__(self, value: _Optional[_Iterable[int]] = ...) -> None: ...

class MapStringKeyStringValue(_message.Message):
    __slots__ = ["value"]
    class ValueEntry(_message.Message):
        __slots__ = ["key", "value"]
        KEY_FIELD_NUMBER: _ClassVar[int]
        VALUE_FIELD_NUMBER: _ClassVar[int]
        key: str
        value: str
        def __init__(self, key: _Optional[str] = ..., value: _Optional[str] = ...) -> None: ...
    VALUE_FIELD_NUMBER: _ClassVar[int]
    value: _containers.ScalarMap[str, str]
    def __init__(self, value: _Optional[_Mapping[str, str]] = ...) -> None: ...

class MapStringKeyMapStringKeyStringValue(_message.Message):
    __slots__ = ["value"]
    class ValueEntry(_message.Message):
        __slots__ = ["key", "value"]
        KEY_FIELD_NUMBER: _ClassVar[int]
        VALUE_FIELD_NUMBER: _ClassVar[int]
        key: str
        value: MapStringKeyStringValue
        def __init__(self, key: _Optional[str] = ..., value: _Optional[_Union[MapStringKeyStringValue, _Mapping]] = ...) -> None: ...
    VALUE_FIELD_NUMBER: _ClassVar[int]
    value: _containers.MessageMap[str, MapStringKeyStringValue]
    def __init__(self, value: _Optional[_Mapping[str, MapStringKeyStringValue]] = ...) -> None: ...

class OpenMetricsFilters(_message.Message):
    __slots__ = ["sequence", "mapping"]
    SEQUENCE_FIELD_NUMBER: _ClassVar[int]
    MAPPING_FIELD_NUMBER: _ClassVar[int]
    sequence: ListStringValue
    mapping: MapStringKeyMapStringKeyStringValue
    def __init__(self, sequence: _Optional[_Union[ListStringValue, _Mapping]] = ..., mapping: _Optional[_Union[MapStringKeyMapStringKeyStringValue, _Mapping]] = ...) -> None: ...

class RunMoment(_message.Message):
    __slots__ = ["run", "value", "metric"]
    RUN_FIELD_NUMBER: _ClassVar[int]
    VALUE_FIELD_NUMBER: _ClassVar[int]
    METRIC_FIELD_NUMBER: _ClassVar[int]
    run: str
    value: float
    metric: str
    def __init__(self, run: _Optional[str] = ..., value: _Optional[float] = ..., metric: _Optional[str] = ...) -> None: ...

class Settings(_message.Message):
    __slots__ = ["api_key", "identity_token_file", "credentials_file", "insecure_disable_ssl", "_offline", "x_sync", "sync_file", "_shared", "run_id", "run_url", "project", "entity", "organization", "x_start_time", "root_dir", "wandb_dir", "log_dir", "log_internal", "ignore_globs", "app_url", "base_url", "x_file_stream_max_bytes", "x_file_stream_transmit_interval", "x_extra_http_headers", "x_file_stream_retry_max", "x_file_stream_retry_wait_min_seconds", "x_file_stream_retry_wait_max_seconds", "x_file_stream_timeout_seconds", "x_file_stream_max_line_bytes", "x_file_transfer_retry_max", "x_file_transfer_retry_wait_min_seconds", "x_file_transfer_retry_wait_max_seconds", "x_file_transfer_timeout_seconds", "x_graphql_retry_max", "x_graphql_retry_wait_min_seconds", "x_graphql_retry_wait_max_seconds", "x_graphql_timeout_seconds", "http_proxy", "https_proxy", "x_proxies", "program", "program_relpath", "_code_path_local", "program_abspath", "_args", "_os", "docker", "x_executable", "_python", "colab_url", "host", "username", "email", "resume", "resume_from", "fork_from", "disable_job_creation", "sweep_url", "x_disable_update_check", "x_disable_meta", "save_code", "disable_git", "disable_git_fork_point", "x_disable_machine_info", "x_disable_stats", "x_stats_buffer_size", "x_stats_sampling_interval", "x_stats_pid", "x_stats_disk_paths", "x_stats_neuron_monitor_config_path", "x_stats_dcgm_exporter", "x_stats_open_metrics_endpoints", "x_stats_open_metrics_filters", "x_stats_open_metrics_http_headers", "x_stats_gpu_device_ids", "x_stats_cpu_count", "x_stats_cpu_logical_count", "x_stats_gpu_count", "x_stats_gpu_type", "x_stats_track_process_tree", "x_label", "x_primary", "x_update_finish_state", "allow_offline_artifacts", "console", "console_multipart", "console_chunk_max_bytes", "console_chunk_max_seconds", "sync_tensorboard", "x_server_side_derived_summary", "x_server_side_expand_glob_metrics", "x_skip_transaction_log", "x_stats_coreweave_metadata_base_url", "x_stats_coreweave_metadata_endpoint", "_aws_lambda", "x_cli_only_mode", "_colab", "x_disable_viewer", "x_flow_control_custom", "x_flow_control_disabled", "x_internal_check_process", "_ipython", "_jupyter", "x_jupyter_root", "_kaggle", "x_live_policy_rate_limit", "x_live_policy_wait_time", "x_log_level", "x_network_buffer", "_noop", "_notebook", "_platform", "x_runqueue_item_id", "x_save_requirements", "x_service_transport", "x_service_wait", "_start_datetime", "_tmp_code_dir", "_windows", "allow_media_symlink", "allow_val_change", "azure_account_url_to_access_key", "code_dir", "config_paths", "deployment", "disable_code", "disable_hints", "disabled", "force", "git_commit", "git_remote", "git_remote_url", "git_root", "heartbeat_seconds", "init_timeout", "is_local", "job_source", "label_disable", "launch", "launch_config_path", "log_symlink_internal", "log_symlink_user", "log_user", "login_timeout", "mode", "notebook_name", "project_url", "quiet", "relogin", "resume_fname", "resumed", "run_group", "run_job_type", "run_mode", "run_name", "run_notes", "run_tags", "sagemaker_disable", "settings_system", "settings_workspace", "show_colors", "show_emoji", "show_errors", "show_info", "show_warnings", "silent", "start_method", "strict", "summary_errors", "summary_timeout", "summary_warnings", "sweep_id", "sweep_param_path", "symlink", "sync_dir", "sync_symlink_latest", "table_raise_on_max_row_limit_exceeded", "timespec", "tmp_dir", "x_jupyter_name", "x_jupyter_path", "job_name"]
    API_KEY_FIELD_NUMBER: _ClassVar[int]
    IDENTITY_TOKEN_FILE_FIELD_NUMBER: _ClassVar[int]
    CREDENTIALS_FILE_FIELD_NUMBER: _ClassVar[int]
    INSECURE_DISABLE_SSL_FIELD_NUMBER: _ClassVar[int]
    _OFFLINE_FIELD_NUMBER: _ClassVar[int]
    X_SYNC_FIELD_NUMBER: _ClassVar[int]
    SYNC_FILE_FIELD_NUMBER: _ClassVar[int]
    _SHARED_FIELD_NUMBER: _ClassVar[int]
    RUN_ID_FIELD_NUMBER: _ClassVar[int]
    RUN_URL_FIELD_NUMBER: _ClassVar[int]
    PROJECT_FIELD_NUMBER: _ClassVar[int]
    ENTITY_FIELD_NUMBER: _ClassVar[int]
    ORGANIZATION_FIELD_NUMBER: _ClassVar[int]
    X_START_TIME_FIELD_NUMBER: _ClassVar[int]
    ROOT_DIR_FIELD_NUMBER: _ClassVar[int]
    WANDB_DIR_FIELD_NUMBER: _ClassVar[int]
    LOG_DIR_FIELD_NUMBER: _ClassVar[int]
    LOG_INTERNAL_FIELD_NUMBER: _ClassVar[int]
    IGNORE_GLOBS_FIELD_NUMBER: _ClassVar[int]
    APP_URL_FIELD_NUMBER: _ClassVar[int]
    BASE_URL_FIELD_NUMBER: _ClassVar[int]
    X_FILE_STREAM_MAX_BYTES_FIELD_NUMBER: _ClassVar[int]
    X_FILE_STREAM_TRANSMIT_INTERVAL_FIELD_NUMBER: _ClassVar[int]
    X_EXTRA_HTTP_HEADERS_FIELD_NUMBER: _ClassVar[int]
    X_FILE_STREAM_RETRY_MAX_FIELD_NUMBER: _ClassVar[int]
    X_FILE_STREAM_RETRY_WAIT_MIN_SECONDS_FIELD_NUMBER: _ClassVar[int]
    X_FILE_STREAM_RETRY_WAIT_MAX_SECONDS_FIELD_NUMBER: _ClassVar[int]
    X_FILE_STREAM_TIMEOUT_SECONDS_FIELD_NUMBER: _ClassVar[int]
    X_FILE_STREAM_MAX_LINE_BYTES_FIELD_NUMBER: _ClassVar[int]
    X_FILE_TRANSFER_RETRY_MAX_FIELD_NUMBER: _ClassVar[int]
    X_FILE_TRANSFER_RETRY_WAIT_MIN_SECONDS_FIELD_NUMBER: _ClassVar[int]
    X_FILE_TRANSFER_RETRY_WAIT_MAX_SECONDS_FIELD_NUMBER: _ClassVar[int]
    X_FILE_TRANSFER_TIMEOUT_SECONDS_FIELD_NUMBER: _ClassVar[int]
    X_GRAPHQL_RETRY_MAX_FIELD_NUMBER: _ClassVar[int]
    X_GRAPHQL_RETRY_WAIT_MIN_SECONDS_FIELD_NUMBER: _ClassVar[int]
    X_GRAPHQL_RETRY_WAIT_MAX_SECONDS_FIELD_NUMBER: _ClassVar[int]
    X_GRAPHQL_TIMEOUT_SECONDS_FIELD_NUMBER: _ClassVar[int]
    HTTP_PROXY_FIELD_NUMBER: _ClassVar[int]
    HTTPS_PROXY_FIELD_NUMBER: _ClassVar[int]
    X_PROXIES_FIELD_NUMBER: _ClassVar[int]
    PROGRAM_FIELD_NUMBER: _ClassVar[int]
    PROGRAM_RELPATH_FIELD_NUMBER: _ClassVar[int]
    _CODE_PATH_LOCAL_FIELD_NUMBER: _ClassVar[int]
    PROGRAM_ABSPATH_FIELD_NUMBER: _ClassVar[int]
    _ARGS_FIELD_NUMBER: _ClassVar[int]
    _OS_FIELD_NUMBER: _ClassVar[int]
    DOCKER_FIELD_NUMBER: _ClassVar[int]
    X_EXECUTABLE_FIELD_NUMBER: _ClassVar[int]
    _PYTHON_FIELD_NUMBER: _ClassVar[int]
    COLAB_URL_FIELD_NUMBER: _ClassVar[int]
    HOST_FIELD_NUMBER: _ClassVar[int]
    USERNAME_FIELD_NUMBER: _ClassVar[int]
    EMAIL_FIELD_NUMBER: _ClassVar[int]
    RESUME_FIELD_NUMBER: _ClassVar[int]
    RESUME_FROM_FIELD_NUMBER: _ClassVar[int]
    FORK_FROM_FIELD_NUMBER: _ClassVar[int]
    DISABLE_JOB_CREATION_FIELD_NUMBER: _ClassVar[int]
    SWEEP_URL_FIELD_NUMBER: _ClassVar[int]
    X_DISABLE_UPDATE_CHECK_FIELD_NUMBER: _ClassVar[int]
    X_DISABLE_META_FIELD_NUMBER: _ClassVar[int]
    SAVE_CODE_FIELD_NUMBER: _ClassVar[int]
    DISABLE_GIT_FIELD_NUMBER: _ClassVar[int]
    DISABLE_GIT_FORK_POINT_FIELD_NUMBER: _ClassVar[int]
    X_DISABLE_MACHINE_INFO_FIELD_NUMBER: _ClassVar[int]
    X_DISABLE_STATS_FIELD_NUMBER: _ClassVar[int]
    X_STATS_BUFFER_SIZE_FIELD_NUMBER: _ClassVar[int]
    X_STATS_SAMPLING_INTERVAL_FIELD_NUMBER: _ClassVar[int]
    X_STATS_PID_FIELD_NUMBER: _ClassVar[int]
    X_STATS_DISK_PATHS_FIELD_NUMBER: _ClassVar[int]
    X_STATS_NEURON_MONITOR_CONFIG_PATH_FIELD_NUMBER: _ClassVar[int]
    X_STATS_DCGM_EXPORTER_FIELD_NUMBER: _ClassVar[int]
    X_STATS_OPEN_METRICS_ENDPOINTS_FIELD_NUMBER: _ClassVar[int]
    X_STATS_OPEN_METRICS_FILTERS_FIELD_NUMBER: _ClassVar[int]
    X_STATS_OPEN_METRICS_HTTP_HEADERS_FIELD_NUMBER: _ClassVar[int]
    X_STATS_GPU_DEVICE_IDS_FIELD_NUMBER: _ClassVar[int]
    X_STATS_CPU_COUNT_FIELD_NUMBER: _ClassVar[int]
    X_STATS_CPU_LOGICAL_COUNT_FIELD_NUMBER: _ClassVar[int]
    X_STATS_GPU_COUNT_FIELD_NUMBER: _ClassVar[int]
    X_STATS_GPU_TYPE_FIELD_NUMBER: _ClassVar[int]
    X_STATS_TRACK_PROCESS_TREE_FIELD_NUMBER: _ClassVar[int]
    X_LABEL_FIELD_NUMBER: _ClassVar[int]
    X_PRIMARY_FIELD_NUMBER: _ClassVar[int]
    X_UPDATE_FINISH_STATE_FIELD_NUMBER: _ClassVar[int]
    ALLOW_OFFLINE_ARTIFACTS_FIELD_NUMBER: _ClassVar[int]
    CONSOLE_FIELD_NUMBER: _ClassVar[int]
    CONSOLE_MULTIPART_FIELD_NUMBER: _ClassVar[int]
    CONSOLE_CHUNK_MAX_BYTES_FIELD_NUMBER: _ClassVar[int]
    CONSOLE_CHUNK_MAX_SECONDS_FIELD_NUMBER: _ClassVar[int]
    SYNC_TENSORBOARD_FIELD_NUMBER: _ClassVar[int]
    X_SERVER_SIDE_DERIVED_SUMMARY_FIELD_NUMBER: _ClassVar[int]
    X_SERVER_SIDE_EXPAND_GLOB_METRICS_FIELD_NUMBER: _ClassVar[int]
    X_SKIP_TRANSACTION_LOG_FIELD_NUMBER: _ClassVar[int]
    X_STATS_COREWEAVE_METADATA_BASE_URL_FIELD_NUMBER: _ClassVar[int]
    X_STATS_COREWEAVE_METADATA_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    _AWS_LAMBDA_FIELD_NUMBER: _ClassVar[int]
    X_CLI_ONLY_MODE_FIELD_NUMBER: _ClassVar[int]
    _COLAB_FIELD_NUMBER: _ClassVar[int]
    X_DISABLE_VIEWER_FIELD_NUMBER: _ClassVar[int]
    X_FLOW_CONTROL_CUSTOM_FIELD_NUMBER: _ClassVar[int]
    X_FLOW_CONTROL_DISABLED_FIELD_NUMBER: _ClassVar[int]
    X_INTERNAL_CHECK_PROCESS_FIELD_NUMBER: _ClassVar[int]
    _IPYTHON_FIELD_NUMBER: _ClassVar[int]
    _JUPYTER_FIELD_NUMBER: _ClassVar[int]
    X_JUPYTER_ROOT_FIELD_NUMBER: _ClassVar[int]
    _KAGGLE_FIELD_NUMBER: _ClassVar[int]
    X_LIVE_POLICY_RATE_LIMIT_FIELD_NUMBER: _ClassVar[int]
    X_LIVE_POLICY_WAIT_TIME_FIELD_NUMBER: _ClassVar[int]
    X_LOG_LEVEL_FIELD_NUMBER: _ClassVar[int]
    X_NETWORK_BUFFER_FIELD_NUMBER: _ClassVar[int]
    _NOOP_FIELD_NUMBER: _ClassVar[int]
    _NOTEBOOK_FIELD_NUMBER: _ClassVar[int]
    _PLATFORM_FIELD_NUMBER: _ClassVar[int]
    X_RUNQUEUE_ITEM_ID_FIELD_NUMBER: _ClassVar[int]
    X_SAVE_REQUIREMENTS_FIELD_NUMBER: _ClassVar[int]
    X_SERVICE_TRANSPORT_FIELD_NUMBER: _ClassVar[int]
    X_SERVICE_WAIT_FIELD_NUMBER: _ClassVar[int]
    _START_DATETIME_FIELD_NUMBER: _ClassVar[int]
    _TMP_CODE_DIR_FIELD_NUMBER: _ClassVar[int]
    _WINDOWS_FIELD_NUMBER: _ClassVar[int]
    ALLOW_MEDIA_SYMLINK_FIELD_NUMBER: _ClassVar[int]
    ALLOW_VAL_CHANGE_FIELD_NUMBER: _ClassVar[int]
    AZURE_ACCOUNT_URL_TO_ACCESS_KEY_FIELD_NUMBER: _ClassVar[int]
    CODE_DIR_FIELD_NUMBER: _ClassVar[int]
    CONFIG_PATHS_FIELD_NUMBER: _ClassVar[int]
    DEPLOYMENT_FIELD_NUMBER: _ClassVar[int]
    DISABLE_CODE_FIELD_NUMBER: _ClassVar[int]
    DISABLE_HINTS_FIELD_NUMBER: _ClassVar[int]
    DISABLED_FIELD_NUMBER: _ClassVar[int]
    FORCE_FIELD_NUMBER: _ClassVar[int]
    GIT_COMMIT_FIELD_NUMBER: _ClassVar[int]
    GIT_REMOTE_FIELD_NUMBER: _ClassVar[int]
    GIT_REMOTE_URL_FIELD_NUMBER: _ClassVar[int]
    GIT_ROOT_FIELD_NUMBER: _ClassVar[int]
    HEARTBEAT_SECONDS_FIELD_NUMBER: _ClassVar[int]
    INIT_TIMEOUT_FIELD_NUMBER: _ClassVar[int]
    IS_LOCAL_FIELD_NUMBER: _ClassVar[int]
    JOB_SOURCE_FIELD_NUMBER: _ClassVar[int]
    LABEL_DISABLE_FIELD_NUMBER: _ClassVar[int]
    LAUNCH_FIELD_NUMBER: _ClassVar[int]
    LAUNCH_CONFIG_PATH_FIELD_NUMBER: _ClassVar[int]
    LOG_SYMLINK_INTERNAL_FIELD_NUMBER: _ClassVar[int]
    LOG_SYMLINK_USER_FIELD_NUMBER: _ClassVar[int]
    LOG_USER_FIELD_NUMBER: _ClassVar[int]
    LOGIN_TIMEOUT_FIELD_NUMBER: _ClassVar[int]
    MODE_FIELD_NUMBER: _ClassVar[int]
    NOTEBOOK_NAME_FIELD_NUMBER: _ClassVar[int]
    PROJECT_URL_FIELD_NUMBER: _ClassVar[int]
    QUIET_FIELD_NUMBER: _ClassVar[int]
    RELOGIN_FIELD_NUMBER: _ClassVar[int]
    RESUME_FNAME_FIELD_NUMBER: _ClassVar[int]
    RESUMED_FIELD_NUMBER: _ClassVar[int]
    RUN_GROUP_FIELD_NUMBER: _ClassVar[int]
    RUN_JOB_TYPE_FIELD_NUMBER: _ClassVar[int]
    RUN_MODE_FIELD_NUMBER: _ClassVar[int]
    RUN_NAME_FIELD_NUMBER: _ClassVar[int]
    RUN_NOTES_FIELD_NUMBER: _ClassVar[int]
    RUN_TAGS_FIELD_NUMBER: _ClassVar[int]
    SAGEMAKER_DISABLE_FIELD_NUMBER: _ClassVar[int]
    SETTINGS_SYSTEM_FIELD_NUMBER: _ClassVar[int]
    SETTINGS_WORKSPACE_FIELD_NUMBER: _ClassVar[int]
    SHOW_COLORS_FIELD_NUMBER: _ClassVar[int]
    SHOW_EMOJI_FIELD_NUMBER: _ClassVar[int]
    SHOW_ERRORS_FIELD_NUMBER: _ClassVar[int]
    SHOW_INFO_FIELD_NUMBER: _ClassVar[int]
    SHOW_WARNINGS_FIELD_NUMBER: _ClassVar[int]
    SILENT_FIELD_NUMBER: _ClassVar[int]
    START_METHOD_FIELD_NUMBER: _ClassVar[int]
    STRICT_FIELD_NUMBER: _ClassVar[int]
    SUMMARY_ERRORS_FIELD_NUMBER: _ClassVar[int]
    SUMMARY_TIMEOUT_FIELD_NUMBER: _ClassVar[int]
    SUMMARY_WARNINGS_FIELD_NUMBER: _ClassVar[int]
    SWEEP_ID_FIELD_NUMBER: _ClassVar[int]
    SWEEP_PARAM_PATH_FIELD_NUMBER: _ClassVar[int]
    SYMLINK_FIELD_NUMBER: _ClassVar[int]
    SYNC_DIR_FIELD_NUMBER: _ClassVar[int]
    SYNC_SYMLINK_LATEST_FIELD_NUMBER: _ClassVar[int]
    TABLE_RAISE_ON_MAX_ROW_LIMIT_EXCEEDED_FIELD_NUMBER: _ClassVar[int]
    TIMESPEC_FIELD_NUMBER: _ClassVar[int]
    TMP_DIR_FIELD_NUMBER: _ClassVar[int]
    X_JUPYTER_NAME_FIELD_NUMBER: _ClassVar[int]
    X_JUPYTER_PATH_FIELD_NUMBER: _ClassVar[int]
    JOB_NAME_FIELD_NUMBER: _ClassVar[int]
    api_key: _wrappers_pb2.StringValue
    identity_token_file: _wrappers_pb2.StringValue
    credentials_file: _wrappers_pb2.StringValue
    insecure_disable_ssl: _wrappers_pb2.BoolValue
    _offline: _wrappers_pb2.BoolValue
    x_sync: _wrappers_pb2.BoolValue
    sync_file: _wrappers_pb2.StringValue
    _shared: _wrappers_pb2.BoolValue
    run_id: _wrappers_pb2.StringValue
    run_url: _wrappers_pb2.StringValue
    project: _wrappers_pb2.StringValue
    entity: _wrappers_pb2.StringValue
    organization: _wrappers_pb2.StringValue
    x_start_time: _wrappers_pb2.DoubleValue
    root_dir: _wrappers_pb2.StringValue
    wandb_dir: _wrappers_pb2.StringValue
    log_dir: _wrappers_pb2.StringValue
    log_internal: _wrappers_pb2.StringValue
    ignore_globs: ListStringValue
    app_url: _wrappers_pb2.StringValue
    base_url: _wrappers_pb2.StringValue
    x_file_stream_max_bytes: _wrappers_pb2.Int32Value
    x_file_stream_transmit_interval: _wrappers_pb2.DoubleValue
    x_extra_http_headers: MapStringKeyStringValue
    x_file_stream_retry_max: _wrappers_pb2.Int32Value
    x_file_stream_retry_wait_min_seconds: _wrappers_pb2.DoubleValue
    x_file_stream_retry_wait_max_seconds: _wrappers_pb2.DoubleValue
    x_file_stream_timeout_seconds: _wrappers_pb2.DoubleValue
    x_file_stream_max_line_bytes: _wrappers_pb2.Int32Value
    x_file_transfer_retry_max: _wrappers_pb2.Int32Value
    x_file_transfer_retry_wait_min_seconds: _wrappers_pb2.DoubleValue
    x_file_transfer_retry_wait_max_seconds: _wrappers_pb2.DoubleValue
    x_file_transfer_timeout_seconds: _wrappers_pb2.DoubleValue
    x_graphql_retry_max: _wrappers_pb2.Int32Value
    x_graphql_retry_wait_min_seconds: _wrappers_pb2.DoubleValue
    x_graphql_retry_wait_max_seconds: _wrappers_pb2.DoubleValue
    x_graphql_timeout_seconds: _wrappers_pb2.DoubleValue
    http_proxy: _wrappers_pb2.StringValue
    https_proxy: _wrappers_pb2.StringValue
    x_proxies: MapStringKeyStringValue
    program: _wrappers_pb2.StringValue
    program_relpath: _wrappers_pb2.StringValue
    _code_path_local: _wrappers_pb2.StringValue
    program_abspath: _wrappers_pb2.StringValue
    _args: ListStringValue
    _os: _wrappers_pb2.StringValue
    docker: _wrappers_pb2.StringValue
    x_executable: _wrappers_pb2.StringValue
    _python: _wrappers_pb2.StringValue
    colab_url: _wrappers_pb2.StringValue
    host: _wrappers_pb2.StringValue
    username: _wrappers_pb2.StringValue
    email: _wrappers_pb2.StringValue
    resume: _wrappers_pb2.StringValue
    resume_from: RunMoment
    fork_from: RunMoment
    disable_job_creation: _wrappers_pb2.BoolValue
    sweep_url: _wrappers_pb2.StringValue
    x_disable_update_check: _wrappers_pb2.BoolValue
    x_disable_meta: _wrappers_pb2.BoolValue
    save_code: _wrappers_pb2.BoolValue
    disable_git: _wrappers_pb2.BoolValue
    disable_git_fork_point: _wrappers_pb2.BoolValue
    x_disable_machine_info: _wrappers_pb2.BoolValue
    x_disable_stats: _wrappers_pb2.BoolValue
    x_stats_buffer_size: _wrappers_pb2.Int32Value
    x_stats_sampling_interval: _wrappers_pb2.DoubleValue
    x_stats_pid: _wrappers_pb2.Int32Value
    x_stats_disk_paths: ListStringValue
    x_stats_neuron_monitor_config_path: _wrappers_pb2.StringValue
    x_stats_dcgm_exporter: _wrappers_pb2.StringValue
    x_stats_open_metrics_endpoints: MapStringKeyStringValue
    x_stats_open_metrics_filters: OpenMetricsFilters
    x_stats_open_metrics_http_headers: MapStringKeyStringValue
    x_stats_gpu_device_ids: ListIntValue
    x_stats_cpu_count: _wrappers_pb2.Int32Value
    x_stats_cpu_logical_count: _wrappers_pb2.Int32Value
    x_stats_gpu_count: _wrappers_pb2.Int32Value
    x_stats_gpu_type: _wrappers_pb2.StringValue
    x_stats_track_process_tree: _wrappers_pb2.BoolValue
    x_label: _wrappers_pb2.StringValue
    x_primary: _wrappers_pb2.BoolValue
    x_update_finish_state: _wrappers_pb2.BoolValue
    allow_offline_artifacts: _wrappers_pb2.BoolValue
    console: _wrappers_pb2.StringValue
    console_multipart: _wrappers_pb2.BoolValue
    console_chunk_max_bytes: _wrappers_pb2.Int32Value
    console_chunk_max_seconds: _wrappers_pb2.Int32Value
    sync_tensorboard: _wrappers_pb2.BoolValue
    x_server_side_derived_summary: _wrappers_pb2.BoolValue
    x_server_side_expand_glob_metrics: _wrappers_pb2.BoolValue
    x_skip_transaction_log: _wrappers_pb2.BoolValue
    x_stats_coreweave_metadata_base_url: _wrappers_pb2.StringValue
    x_stats_coreweave_metadata_endpoint: _wrappers_pb2.StringValue
    _aws_lambda: _wrappers_pb2.BoolValue
    x_cli_only_mode: _wrappers_pb2.BoolValue
    _colab: _wrappers_pb2.BoolValue
    x_disable_viewer: _wrappers_pb2.BoolValue
    x_flow_control_custom: _wrappers_pb2.BoolValue
    x_flow_control_disabled: _wrappers_pb2.BoolValue
    x_internal_check_process: _wrappers_pb2.DoubleValue
    _ipython: _wrappers_pb2.BoolValue
    _jupyter: _wrappers_pb2.BoolValue
    x_jupyter_root: _wrappers_pb2.StringValue
    _kaggle: _wrappers_pb2.BoolValue
    x_live_policy_rate_limit: _wrappers_pb2.Int32Value
    x_live_policy_wait_time: _wrappers_pb2.Int32Value
    x_log_level: _wrappers_pb2.Int32Value
    x_network_buffer: _wrappers_pb2.Int32Value
    _noop: _wrappers_pb2.BoolValue
    _notebook: _wrappers_pb2.BoolValue
    _platform: _wrappers_pb2.StringValue
    x_runqueue_item_id: _wrappers_pb2.StringValue
    x_save_requirements: _wrappers_pb2.BoolValue
    x_service_transport: _wrappers_pb2.StringValue
    x_service_wait: _wrappers_pb2.DoubleValue
    _start_datetime: _wrappers_pb2.StringValue
    _tmp_code_dir: _wrappers_pb2.StringValue
    _windows: _wrappers_pb2.BoolValue
    allow_media_symlink: _wrappers_pb2.BoolValue
    allow_val_change: _wrappers_pb2.BoolValue
    azure_account_url_to_access_key: MapStringKeyStringValue
    code_dir: _wrappers_pb2.StringValue
    config_paths: ListStringValue
    deployment: _wrappers_pb2.StringValue
    disable_code: _wrappers_pb2.BoolValue
    disable_hints: _wrappers_pb2.BoolValue
    disabled: _wrappers_pb2.BoolValue
    force: _wrappers_pb2.BoolValue
    git_commit: _wrappers_pb2.StringValue
    git_remote: _wrappers_pb2.StringValue
    git_remote_url: _wrappers_pb2.StringValue
    git_root: _wrappers_pb2.StringValue
    heartbeat_seconds: _wrappers_pb2.Int32Value
    init_timeout: _wrappers_pb2.DoubleValue
    is_local: _wrappers_pb2.BoolValue
    job_source: _wrappers_pb2.StringValue
    label_disable: _wrappers_pb2.BoolValue
    launch: _wrappers_pb2.BoolValue
    launch_config_path: _wrappers_pb2.StringValue
    log_symlink_internal: _wrappers_pb2.StringValue
    log_symlink_user: _wrappers_pb2.StringValue
    log_user: _wrappers_pb2.StringValue
    login_timeout: _wrappers_pb2.DoubleValue
    mode: _wrappers_pb2.StringValue
    notebook_name: _wrappers_pb2.StringValue
    project_url: _wrappers_pb2.StringValue
    quiet: _wrappers_pb2.BoolValue
    relogin: _wrappers_pb2.BoolValue
    resume_fname: _wrappers_pb2.StringValue
    resumed: _wrappers_pb2.BoolValue
    run_group: _wrappers_pb2.StringValue
    run_job_type: _wrappers_pb2.StringValue
    run_mode: _wrappers_pb2.StringValue
    run_name: _wrappers_pb2.StringValue
    run_notes: _wrappers_pb2.StringValue
    run_tags: ListStringValue
    sagemaker_disable: _wrappers_pb2.BoolValue
    settings_system: _wrappers_pb2.StringValue
    settings_workspace: _wrappers_pb2.StringValue
    show_colors: _wrappers_pb2.BoolValue
    show_emoji: _wrappers_pb2.BoolValue
    show_errors: _wrappers_pb2.BoolValue
    show_info: _wrappers_pb2.BoolValue
    show_warnings: _wrappers_pb2.BoolValue
    silent: _wrappers_pb2.BoolValue
    start_method: _wrappers_pb2.StringValue
    strict: _wrappers_pb2.BoolValue
    summary_errors: _wrappers_pb2.Int32Value
    summary_timeout: _wrappers_pb2.Int32Value
    summary_warnings: _wrappers_pb2.Int32Value
    sweep_id: _wrappers_pb2.StringValue
    sweep_param_path: _wrappers_pb2.StringValue
    symlink: _wrappers_pb2.BoolValue
    sync_dir: _wrappers_pb2.StringValue
    sync_symlink_latest: _wrappers_pb2.StringValue
    table_raise_on_max_row_limit_exceeded: _wrappers_pb2.BoolValue
    timespec: _wrappers_pb2.StringValue
    tmp_dir: _wrappers_pb2.StringValue
    x_jupyter_name: _wrappers_pb2.StringValue
    x_jupyter_path: _wrappers_pb2.StringValue
    job_name: _wrappers_pb2.StringValue
    def __init__(self, api_key: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., identity_token_file: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., credentials_file: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., insecure_disable_ssl: _Optional[_Union[_wrappers_pb2.BoolValue, _Mapping]] = ..., _offline: _Optional[_Union[_wrappers_pb2.BoolValue, _Mapping]] = ..., x_sync: _Optional[_Union[_wrappers_pb2.BoolValue, _Mapping]] = ..., sync_file: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., _shared: _Optional[_Union[_wrappers_pb2.BoolValue, _Mapping]] = ..., run_id: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., run_url: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., project: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., entity: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., organization: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., x_start_time: _Optional[_Union[_wrappers_pb2.DoubleValue, _Mapping]] = ..., root_dir: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., wandb_dir: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., log_dir: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., log_internal: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., ignore_globs: _Optional[_Union[ListStringValue, _Mapping]] = ..., app_url: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., base_url: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., x_file_stream_max_bytes: _Optional[_Union[_wrappers_pb2.Int32Value, _Mapping]] = ..., x_file_stream_transmit_interval: _Optional[_Union[_wrappers_pb2.DoubleValue, _Mapping]] = ..., x_extra_http_headers: _Optional[_Union[MapStringKeyStringValue, _Mapping]] = ..., x_file_stream_retry_max: _Optional[_Union[_wrappers_pb2.Int32Value, _Mapping]] = ..., x_file_stream_retry_wait_min_seconds: _Optional[_Union[_wrappers_pb2.DoubleValue, _Mapping]] = ..., x_file_stream_retry_wait_max_seconds: _Optional[_Union[_wrappers_pb2.DoubleValue, _Mapping]] = ..., x_file_stream_timeout_seconds: _Optional[_Union[_wrappers_pb2.DoubleValue, _Mapping]] = ..., x_file_stream_max_line_bytes: _Optional[_Union[_wrappers_pb2.Int32Value, _Mapping]] = ..., x_file_transfer_retry_max: _Optional[_Union[_wrappers_pb2.Int32Value, _Mapping]] = ..., x_file_transfer_retry_wait_min_seconds: _Optional[_Union[_wrappers_pb2.DoubleValue, _Mapping]] = ..., x_file_transfer_retry_wait_max_seconds: _Optional[_Union[_wrappers_pb2.DoubleValue, _Mapping]] = ..., x_file_transfer_timeout_seconds: _Optional[_Union[_wrappers_pb2.DoubleValue, _Mapping]] = ..., x_graphql_retry_max: _Optional[_Union[_wrappers_pb2.Int32Value, _Mapping]] = ..., x_graphql_retry_wait_min_seconds: _Optional[_Union[_wrappers_pb2.DoubleValue, _Mapping]] = ..., x_graphql_retry_wait_max_seconds: _Optional[_Union[_wrappers_pb2.DoubleValue, _Mapping]] = ..., x_graphql_timeout_seconds: _Optional[_Union[_wrappers_pb2.DoubleValue, _Mapping]] = ..., http_proxy: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., https_proxy: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., x_proxies: _Optional[_Union[MapStringKeyStringValue, _Mapping]] = ..., program: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., program_relpath: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., _code_path_local: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., program_abspath: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., _args: _Optional[_Union[ListStringValue, _Mapping]] = ..., _os: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., docker: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., x_executable: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., _python: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., colab_url: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., host: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., username: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., email: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., resume: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., resume_from: _Optional[_Union[RunMoment, _Mapping]] = ..., fork_from: _Optional[_Union[RunMoment, _Mapping]] = ..., disable_job_creation: _Optional[_Union[_wrappers_pb2.BoolValue, _Mapping]] = ..., sweep_url: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., x_disable_update_check: _Optional[_Union[_wrappers_pb2.BoolValue, _Mapping]] = ..., x_disable_meta: _Optional[_Union[_wrappers_pb2.BoolValue, _Mapping]] = ..., save_code: _Optional[_Union[_wrappers_pb2.BoolValue, _Mapping]] = ..., disable_git: _Optional[_Union[_wrappers_pb2.BoolValue, _Mapping]] = ..., disable_git_fork_point: _Optional[_Union[_wrappers_pb2.BoolValue, _Mapping]] = ..., x_disable_machine_info: _Optional[_Union[_wrappers_pb2.BoolValue, _Mapping]] = ..., x_disable_stats: _Optional[_Union[_wrappers_pb2.BoolValue, _Mapping]] = ..., x_stats_buffer_size: _Optional[_Union[_wrappers_pb2.Int32Value, _Mapping]] = ..., x_stats_sampling_interval: _Optional[_Union[_wrappers_pb2.DoubleValue, _Mapping]] = ..., x_stats_pid: _Optional[_Union[_wrappers_pb2.Int32Value, _Mapping]] = ..., x_stats_disk_paths: _Optional[_Union[ListStringValue, _Mapping]] = ..., x_stats_neuron_monitor_config_path: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., x_stats_dcgm_exporter: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., x_stats_open_metrics_endpoints: _Optional[_Union[MapStringKeyStringValue, _Mapping]] = ..., x_stats_open_metrics_filters: _Optional[_Union[OpenMetricsFilters, _Mapping]] = ..., x_stats_open_metrics_http_headers: _Optional[_Union[MapStringKeyStringValue, _Mapping]] = ..., x_stats_gpu_device_ids: _Optional[_Union[ListIntValue, _Mapping]] = ..., x_stats_cpu_count: _Optional[_Union[_wrappers_pb2.Int32Value, _Mapping]] = ..., x_stats_cpu_logical_count: _Optional[_Union[_wrappers_pb2.Int32Value, _Mapping]] = ..., x_stats_gpu_count: _Optional[_Union[_wrappers_pb2.Int32Value, _Mapping]] = ..., x_stats_gpu_type: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., x_stats_track_process_tree: _Optional[_Union[_wrappers_pb2.BoolValue, _Mapping]] = ..., x_label: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., x_primary: _Optional[_Union[_wrappers_pb2.BoolValue, _Mapping]] = ..., x_update_finish_state: _Optional[_Union[_wrappers_pb2.BoolValue, _Mapping]] = ..., allow_offline_artifacts: _Optional[_Union[_wrappers_pb2.BoolValue, _Mapping]] = ..., console: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., console_multipart: _Optional[_Union[_wrappers_pb2.BoolValue, _Mapping]] = ..., console_chunk_max_bytes: _Optional[_Union[_wrappers_pb2.Int32Value, _Mapping]] = ..., console_chunk_max_seconds: _Optional[_Union[_wrappers_pb2.Int32Value, _Mapping]] = ..., sync_tensorboard: _Optional[_Union[_wrappers_pb2.BoolValue, _Mapping]] = ..., x_server_side_derived_summary: _Optional[_Union[_wrappers_pb2.BoolValue, _Mapping]] = ..., x_server_side_expand_glob_metrics: _Optional[_Union[_wrappers_pb2.BoolValue, _Mapping]] = ..., x_skip_transaction_log: _Optional[_Union[_wrappers_pb2.BoolValue, _Mapping]] = ..., x_stats_coreweave_metadata_base_url: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., x_stats_coreweave_metadata_endpoint: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., _aws_lambda: _Optional[_Union[_wrappers_pb2.BoolValue, _Mapping]] = ..., x_cli_only_mode: _Optional[_Union[_wrappers_pb2.BoolValue, _Mapping]] = ..., _colab: _Optional[_Union[_wrappers_pb2.BoolValue, _Mapping]] = ..., x_disable_viewer: _Optional[_Union[_wrappers_pb2.BoolValue, _Mapping]] = ..., x_flow_control_custom: _Optional[_Union[_wrappers_pb2.BoolValue, _Mapping]] = ..., x_flow_control_disabled: _Optional[_Union[_wrappers_pb2.BoolValue, _Mapping]] = ..., x_internal_check_process: _Optional[_Union[_wrappers_pb2.DoubleValue, _Mapping]] = ..., _ipython: _Optional[_Union[_wrappers_pb2.BoolValue, _Mapping]] = ..., _jupyter: _Optional[_Union[_wrappers_pb2.BoolValue, _Mapping]] = ..., x_jupyter_root: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., _kaggle: _Optional[_Union[_wrappers_pb2.BoolValue, _Mapping]] = ..., x_live_policy_rate_limit: _Optional[_Union[_wrappers_pb2.Int32Value, _Mapping]] = ..., x_live_policy_wait_time: _Optional[_Union[_wrappers_pb2.Int32Value, _Mapping]] = ..., x_log_level: _Optional[_Union[_wrappers_pb2.Int32Value, _Mapping]] = ..., x_network_buffer: _Optional[_Union[_wrappers_pb2.Int32Value, _Mapping]] = ..., _noop: _Optional[_Union[_wrappers_pb2.BoolValue, _Mapping]] = ..., _notebook: _Optional[_Union[_wrappers_pb2.BoolValue, _Mapping]] = ..., _platform: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., x_runqueue_item_id: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., x_save_requirements: _Optional[_Union[_wrappers_pb2.BoolValue, _Mapping]] = ..., x_service_transport: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., x_service_wait: _Optional[_Union[_wrappers_pb2.DoubleValue, _Mapping]] = ..., _start_datetime: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., _tmp_code_dir: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., _windows: _Optional[_Union[_wrappers_pb2.BoolValue, _Mapping]] = ..., allow_media_symlink: _Optional[_Union[_wrappers_pb2.BoolValue, _Mapping]] = ..., allow_val_change: _Optional[_Union[_wrappers_pb2.BoolValue, _Mapping]] = ..., azure_account_url_to_access_key: _Optional[_Union[MapStringKeyStringValue, _Mapping]] = ..., code_dir: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., config_paths: _Optional[_Union[ListStringValue, _Mapping]] = ..., deployment: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., disable_code: _Optional[_Union[_wrappers_pb2.BoolValue, _Mapping]] = ..., disable_hints: _Optional[_Union[_wrappers_pb2.BoolValue, _Mapping]] = ..., disabled: _Optional[_Union[_wrappers_pb2.BoolValue, _Mapping]] = ..., force: _Optional[_Union[_wrappers_pb2.BoolValue, _Mapping]] = ..., git_commit: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., git_remote: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., git_remote_url: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., git_root: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., heartbeat_seconds: _Optional[_Union[_wrappers_pb2.Int32Value, _Mapping]] = ..., init_timeout: _Optional[_Union[_wrappers_pb2.DoubleValue, _Mapping]] = ..., is_local: _Optional[_Union[_wrappers_pb2.BoolValue, _Mapping]] = ..., job_source: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., label_disable: _Optional[_Union[_wrappers_pb2.BoolValue, _Mapping]] = ..., launch: _Optional[_Union[_wrappers_pb2.BoolValue, _Mapping]] = ..., launch_config_path: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., log_symlink_internal: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., log_symlink_user: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., log_user: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., login_timeout: _Optional[_Union[_wrappers_pb2.DoubleValue, _Mapping]] = ..., mode: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., notebook_name: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., project_url: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., quiet: _Optional[_Union[_wrappers_pb2.BoolValue, _Mapping]] = ..., relogin: _Optional[_Union[_wrappers_pb2.BoolValue, _Mapping]] = ..., resume_fname: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., resumed: _Optional[_Union[_wrappers_pb2.BoolValue, _Mapping]] = ..., run_group: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., run_job_type: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., run_mode: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., run_name: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., run_notes: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., run_tags: _Optional[_Union[ListStringValue, _Mapping]] = ..., sagemaker_disable: _Optional[_Union[_wrappers_pb2.BoolValue, _Mapping]] = ..., settings_system: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., settings_workspace: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., show_colors: _Optional[_Union[_wrappers_pb2.BoolValue, _Mapping]] = ..., show_emoji: _Optional[_Union[_wrappers_pb2.BoolValue, _Mapping]] = ..., show_errors: _Optional[_Union[_wrappers_pb2.BoolValue, _Mapping]] = ..., show_info: _Optional[_Union[_wrappers_pb2.BoolValue, _Mapping]] = ..., show_warnings: _Optional[_Union[_wrappers_pb2.BoolValue, _Mapping]] = ..., silent: _Optional[_Union[_wrappers_pb2.BoolValue, _Mapping]] = ..., start_method: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., strict: _Optional[_Union[_wrappers_pb2.BoolValue, _Mapping]] = ..., summary_errors: _Optional[_Union[_wrappers_pb2.Int32Value, _Mapping]] = ..., summary_timeout: _Optional[_Union[_wrappers_pb2.Int32Value, _Mapping]] = ..., summary_warnings: _Optional[_Union[_wrappers_pb2.Int32Value, _Mapping]] = ..., sweep_id: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., sweep_param_path: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., symlink: _Optional[_Union[_wrappers_pb2.BoolValue, _Mapping]] = ..., sync_dir: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., sync_symlink_latest: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., table_raise_on_max_row_limit_exceeded: _Optional[_Union[_wrappers_pb2.BoolValue, _Mapping]] = ..., timespec: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., tmp_dir: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., x_jupyter_name: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., x_jupyter_path: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ..., job_name: _Optional[_Union[_wrappers_pb2.StringValue, _Mapping]] = ...) -> None: ...
