"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class _RecordInfo(google.protobuf.message.Message):
    """
    _RecordInfo, _RequestInfo: extra info for all records and requests
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class HeadersEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

    STREAM_ID_FIELD_NUMBER: builtins.int
    _TRACELOG_ID_FIELD_NUMBER: builtins.int
    HEADERS_FIELD_NUMBER: builtins.int
    stream_id: builtins.str
    _tracelog_id: builtins.str
    @property
    def headers(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    def __init__(
        self,
        *,
        stream_id: builtins.str = ...,
        _tracelog_id: builtins.str = ...,
        headers: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["_tracelog_id", b"_tracelog_id", "headers", b"headers", "stream_id", b"stream_id"]) -> None: ...

global____RecordInfo = _RecordInfo

@typing_extensions.final
class _RequestInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STREAM_ID_FIELD_NUMBER: builtins.int
    stream_id: builtins.str
    def __init__(
        self,
        *,
        stream_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["stream_id", b"stream_id"]) -> None: ...

global____RequestInfo = _RequestInfo

@typing_extensions.final
class _ResultInfo(google.protobuf.message.Message):
    """
    _ResultInfo: extra info for all results
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    _TRACELOG_ID_FIELD_NUMBER: builtins.int
    _tracelog_id: builtins.str
    def __init__(
        self,
        *,
        _tracelog_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["_tracelog_id", b"_tracelog_id"]) -> None: ...

global____ResultInfo = _ResultInfo
