from wandb.proto import wandb_base_pb2 as _wandb_base_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from typing import ClassVar as _ClassVar, Mapping as _Mapping, Optional as _Optional, Union as _Union

DESCRIPTOR: _descriptor.FileDescriptor

class TelemetryRecord(_message.Message):
    __slots__ = ["imports_init", "imports_finish", "feature", "python_version", "cli_version", "huggingface_version", "env", "label", "deprecated", "issues", "core_version", "platform", "_info"]
    IMPORTS_INIT_FIELD_NUMBER: _ClassVar[int]
    IMPORTS_FINISH_FIELD_NUMBER: _ClassVar[int]
    FEATURE_FIELD_NUMBER: _ClassVar[int]
    PYTHON_VERSION_FIELD_NUMBER: _ClassVar[int]
    CLI_VERSION_FIELD_NUMBER: _ClassVar[int]
    HUGGINGFACE_VERSION_FIELD_NUMBER: _ClassVar[int]
    ENV_FIELD_NUMBER: _ClassVar[int]
    LABEL_FIELD_NUMBER: _ClassVar[int]
    DEPRECATED_FIELD_NUMBER: _ClassVar[int]
    ISSUES_FIELD_NUMBER: _ClassVar[int]
    CORE_VERSION_FIELD_NUMBER: _ClassVar[int]
    PLATFORM_FIELD_NUMBER: _ClassVar[int]
    _INFO_FIELD_NUMBER: _ClassVar[int]
    imports_init: Imports
    imports_finish: Imports
    feature: Feature
    python_version: str
    cli_version: str
    huggingface_version: str
    env: Env
    label: Labels
    deprecated: Deprecated
    issues: Issues
    core_version: str
    platform: str
    _info: _wandb_base_pb2._RecordInfo
    def __init__(self, imports_init: _Optional[_Union[Imports, _Mapping]] = ..., imports_finish: _Optional[_Union[Imports, _Mapping]] = ..., feature: _Optional[_Union[Feature, _Mapping]] = ..., python_version: _Optional[str] = ..., cli_version: _Optional[str] = ..., huggingface_version: _Optional[str] = ..., env: _Optional[_Union[Env, _Mapping]] = ..., label: _Optional[_Union[Labels, _Mapping]] = ..., deprecated: _Optional[_Union[Deprecated, _Mapping]] = ..., issues: _Optional[_Union[Issues, _Mapping]] = ..., core_version: _Optional[str] = ..., platform: _Optional[str] = ..., _info: _Optional[_Union[_wandb_base_pb2._RecordInfo, _Mapping]] = ...) -> None: ...

class TelemetryResult(_message.Message):
    __slots__ = []
    def __init__(self) -> None: ...

class Imports(_message.Message):
    __slots__ = ["torch", "keras", "tensorflow", "fastai", "sklearn", "xgboost", "catboost", "lightgbm", "pytorch_lightning", "ignite", "transformers", "jax", "metaflow", "allennlp", "autogluon", "autokeras", "catalyst", "deepchem", "deepctr", "pycaret", "pytorchvideo", "ray", "simpletransformers", "skorch", "spacy", "flash", "optuna", "recbole", "mmcv", "mmdet", "torchdrug", "torchtext", "torchvision", "elegy", "detectron2", "flair", "flax", "syft", "TTS", "monai", "huggingface_hub", "hydra", "datasets", "sacred", "joblib", "dask", "paddleocr", "ppdet", "paddleseg", "paddlenlp", "mmseg", "mmocr", "mmcls", "timm", "fairseq", "deepchecks", "composer", "sparseml", "anomalib", "zenml", "colossalai", "accelerate", "merlin", "nanodet", "segmentation_models_pytorch", "sentence_transformers", "dgl", "torch_geometric", "jina", "kornia", "albumentations", "keras_cv", "mmengine", "diffusers", "trl", "trlx", "langchain", "llama_index", "stability_sdk", "prefect", "prefect_ray", "pinecone", "chromadb", "weaviate", "promptlayer", "openai", "cohere", "anthropic", "peft", "optimum", "evaluate", "langflow", "keras_core", "lightning_fabric", "curated_transformers", "orjson", "lightning", "dspy"]
    TORCH_FIELD_NUMBER: _ClassVar[int]
    KERAS_FIELD_NUMBER: _ClassVar[int]
    TENSORFLOW_FIELD_NUMBER: _ClassVar[int]
    FASTAI_FIELD_NUMBER: _ClassVar[int]
    SKLEARN_FIELD_NUMBER: _ClassVar[int]
    XGBOOST_FIELD_NUMBER: _ClassVar[int]
    CATBOOST_FIELD_NUMBER: _ClassVar[int]
    LIGHTGBM_FIELD_NUMBER: _ClassVar[int]
    PYTORCH_LIGHTNING_FIELD_NUMBER: _ClassVar[int]
    IGNITE_FIELD_NUMBER: _ClassVar[int]
    TRANSFORMERS_FIELD_NUMBER: _ClassVar[int]
    JAX_FIELD_NUMBER: _ClassVar[int]
    METAFLOW_FIELD_NUMBER: _ClassVar[int]
    ALLENNLP_FIELD_NUMBER: _ClassVar[int]
    AUTOGLUON_FIELD_NUMBER: _ClassVar[int]
    AUTOKERAS_FIELD_NUMBER: _ClassVar[int]
    CATALYST_FIELD_NUMBER: _ClassVar[int]
    DEEPCHEM_FIELD_NUMBER: _ClassVar[int]
    DEEPCTR_FIELD_NUMBER: _ClassVar[int]
    PYCARET_FIELD_NUMBER: _ClassVar[int]
    PYTORCHVIDEO_FIELD_NUMBER: _ClassVar[int]
    RAY_FIELD_NUMBER: _ClassVar[int]
    SIMPLETRANSFORMERS_FIELD_NUMBER: _ClassVar[int]
    SKORCH_FIELD_NUMBER: _ClassVar[int]
    SPACY_FIELD_NUMBER: _ClassVar[int]
    FLASH_FIELD_NUMBER: _ClassVar[int]
    OPTUNA_FIELD_NUMBER: _ClassVar[int]
    RECBOLE_FIELD_NUMBER: _ClassVar[int]
    MMCV_FIELD_NUMBER: _ClassVar[int]
    MMDET_FIELD_NUMBER: _ClassVar[int]
    TORCHDRUG_FIELD_NUMBER: _ClassVar[int]
    TORCHTEXT_FIELD_NUMBER: _ClassVar[int]
    TORCHVISION_FIELD_NUMBER: _ClassVar[int]
    ELEGY_FIELD_NUMBER: _ClassVar[int]
    DETECTRON2_FIELD_NUMBER: _ClassVar[int]
    FLAIR_FIELD_NUMBER: _ClassVar[int]
    FLAX_FIELD_NUMBER: _ClassVar[int]
    SYFT_FIELD_NUMBER: _ClassVar[int]
    TTS_FIELD_NUMBER: _ClassVar[int]
    MONAI_FIELD_NUMBER: _ClassVar[int]
    HUGGINGFACE_HUB_FIELD_NUMBER: _ClassVar[int]
    HYDRA_FIELD_NUMBER: _ClassVar[int]
    DATASETS_FIELD_NUMBER: _ClassVar[int]
    SACRED_FIELD_NUMBER: _ClassVar[int]
    JOBLIB_FIELD_NUMBER: _ClassVar[int]
    DASK_FIELD_NUMBER: _ClassVar[int]
    PADDLEOCR_FIELD_NUMBER: _ClassVar[int]
    PPDET_FIELD_NUMBER: _ClassVar[int]
    PADDLESEG_FIELD_NUMBER: _ClassVar[int]
    PADDLENLP_FIELD_NUMBER: _ClassVar[int]
    MMSEG_FIELD_NUMBER: _ClassVar[int]
    MMOCR_FIELD_NUMBER: _ClassVar[int]
    MMCLS_FIELD_NUMBER: _ClassVar[int]
    TIMM_FIELD_NUMBER: _ClassVar[int]
    FAIRSEQ_FIELD_NUMBER: _ClassVar[int]
    DEEPCHECKS_FIELD_NUMBER: _ClassVar[int]
    COMPOSER_FIELD_NUMBER: _ClassVar[int]
    SPARSEML_FIELD_NUMBER: _ClassVar[int]
    ANOMALIB_FIELD_NUMBER: _ClassVar[int]
    ZENML_FIELD_NUMBER: _ClassVar[int]
    COLOSSALAI_FIELD_NUMBER: _ClassVar[int]
    ACCELERATE_FIELD_NUMBER: _ClassVar[int]
    MERLIN_FIELD_NUMBER: _ClassVar[int]
    NANODET_FIELD_NUMBER: _ClassVar[int]
    SEGMENTATION_MODELS_PYTORCH_FIELD_NUMBER: _ClassVar[int]
    SENTENCE_TRANSFORMERS_FIELD_NUMBER: _ClassVar[int]
    DGL_FIELD_NUMBER: _ClassVar[int]
    TORCH_GEOMETRIC_FIELD_NUMBER: _ClassVar[int]
    JINA_FIELD_NUMBER: _ClassVar[int]
    KORNIA_FIELD_NUMBER: _ClassVar[int]
    ALBUMENTATIONS_FIELD_NUMBER: _ClassVar[int]
    KERAS_CV_FIELD_NUMBER: _ClassVar[int]
    MMENGINE_FIELD_NUMBER: _ClassVar[int]
    DIFFUSERS_FIELD_NUMBER: _ClassVar[int]
    TRL_FIELD_NUMBER: _ClassVar[int]
    TRLX_FIELD_NUMBER: _ClassVar[int]
    LANGCHAIN_FIELD_NUMBER: _ClassVar[int]
    LLAMA_INDEX_FIELD_NUMBER: _ClassVar[int]
    STABILITY_SDK_FIELD_NUMBER: _ClassVar[int]
    PREFECT_FIELD_NUMBER: _ClassVar[int]
    PREFECT_RAY_FIELD_NUMBER: _ClassVar[int]
    PINECONE_FIELD_NUMBER: _ClassVar[int]
    CHROMADB_FIELD_NUMBER: _ClassVar[int]
    WEAVIATE_FIELD_NUMBER: _ClassVar[int]
    PROMPTLAYER_FIELD_NUMBER: _ClassVar[int]
    OPENAI_FIELD_NUMBER: _ClassVar[int]
    COHERE_FIELD_NUMBER: _ClassVar[int]
    ANTHROPIC_FIELD_NUMBER: _ClassVar[int]
    PEFT_FIELD_NUMBER: _ClassVar[int]
    OPTIMUM_FIELD_NUMBER: _ClassVar[int]
    EVALUATE_FIELD_NUMBER: _ClassVar[int]
    LANGFLOW_FIELD_NUMBER: _ClassVar[int]
    KERAS_CORE_FIELD_NUMBER: _ClassVar[int]
    LIGHTNING_FABRIC_FIELD_NUMBER: _ClassVar[int]
    CURATED_TRANSFORMERS_FIELD_NUMBER: _ClassVar[int]
    ORJSON_FIELD_NUMBER: _ClassVar[int]
    LIGHTNING_FIELD_NUMBER: _ClassVar[int]
    DSPY_FIELD_NUMBER: _ClassVar[int]
    torch: bool
    keras: bool
    tensorflow: bool
    fastai: bool
    sklearn: bool
    xgboost: bool
    catboost: bool
    lightgbm: bool
    pytorch_lightning: bool
    ignite: bool
    transformers: bool
    jax: bool
    metaflow: bool
    allennlp: bool
    autogluon: bool
    autokeras: bool
    catalyst: bool
    deepchem: bool
    deepctr: bool
    pycaret: bool
    pytorchvideo: bool
    ray: bool
    simpletransformers: bool
    skorch: bool
    spacy: bool
    flash: bool
    optuna: bool
    recbole: bool
    mmcv: bool
    mmdet: bool
    torchdrug: bool
    torchtext: bool
    torchvision: bool
    elegy: bool
    detectron2: bool
    flair: bool
    flax: bool
    syft: bool
    TTS: bool
    monai: bool
    huggingface_hub: bool
    hydra: bool
    datasets: bool
    sacred: bool
    joblib: bool
    dask: bool
    paddleocr: bool
    ppdet: bool
    paddleseg: bool
    paddlenlp: bool
    mmseg: bool
    mmocr: bool
    mmcls: bool
    timm: bool
    fairseq: bool
    deepchecks: bool
    composer: bool
    sparseml: bool
    anomalib: bool
    zenml: bool
    colossalai: bool
    accelerate: bool
    merlin: bool
    nanodet: bool
    segmentation_models_pytorch: bool
    sentence_transformers: bool
    dgl: bool
    torch_geometric: bool
    jina: bool
    kornia: bool
    albumentations: bool
    keras_cv: bool
    mmengine: bool
    diffusers: bool
    trl: bool
    trlx: bool
    langchain: bool
    llama_index: bool
    stability_sdk: bool
    prefect: bool
    prefect_ray: bool
    pinecone: bool
    chromadb: bool
    weaviate: bool
    promptlayer: bool
    openai: bool
    cohere: bool
    anthropic: bool
    peft: bool
    optimum: bool
    evaluate: bool
    langflow: bool
    keras_core: bool
    lightning_fabric: bool
    curated_transformers: bool
    orjson: bool
    lightning: bool
    dspy: bool
    def __init__(self, torch: bool = ..., keras: bool = ..., tensorflow: bool = ..., fastai: bool = ..., sklearn: bool = ..., xgboost: bool = ..., catboost: bool = ..., lightgbm: bool = ..., pytorch_lightning: bool = ..., ignite: bool = ..., transformers: bool = ..., jax: bool = ..., metaflow: bool = ..., allennlp: bool = ..., autogluon: bool = ..., autokeras: bool = ..., catalyst: bool = ..., deepchem: bool = ..., deepctr: bool = ..., pycaret: bool = ..., pytorchvideo: bool = ..., ray: bool = ..., simpletransformers: bool = ..., skorch: bool = ..., spacy: bool = ..., flash: bool = ..., optuna: bool = ..., recbole: bool = ..., mmcv: bool = ..., mmdet: bool = ..., torchdrug: bool = ..., torchtext: bool = ..., torchvision: bool = ..., elegy: bool = ..., detectron2: bool = ..., flair: bool = ..., flax: bool = ..., syft: bool = ..., TTS: bool = ..., monai: bool = ..., huggingface_hub: bool = ..., hydra: bool = ..., datasets: bool = ..., sacred: bool = ..., joblib: bool = ..., dask: bool = ..., paddleocr: bool = ..., ppdet: bool = ..., paddleseg: bool = ..., paddlenlp: bool = ..., mmseg: bool = ..., mmocr: bool = ..., mmcls: bool = ..., timm: bool = ..., fairseq: bool = ..., deepchecks: bool = ..., composer: bool = ..., sparseml: bool = ..., anomalib: bool = ..., zenml: bool = ..., colossalai: bool = ..., accelerate: bool = ..., merlin: bool = ..., nanodet: bool = ..., segmentation_models_pytorch: bool = ..., sentence_transformers: bool = ..., dgl: bool = ..., torch_geometric: bool = ..., jina: bool = ..., kornia: bool = ..., albumentations: bool = ..., keras_cv: bool = ..., mmengine: bool = ..., diffusers: bool = ..., trl: bool = ..., trlx: bool = ..., langchain: bool = ..., llama_index: bool = ..., stability_sdk: bool = ..., prefect: bool = ..., prefect_ray: bool = ..., pinecone: bool = ..., chromadb: bool = ..., weaviate: bool = ..., promptlayer: bool = ..., openai: bool = ..., cohere: bool = ..., anthropic: bool = ..., peft: bool = ..., optimum: bool = ..., evaluate: bool = ..., langflow: bool = ..., keras_core: bool = ..., lightning_fabric: bool = ..., curated_transformers: bool = ..., orjson: bool = ..., lightning: bool = ..., dspy: bool = ...) -> None: ...

class Feature(_message.Message):
    __slots__ = ["watch", "finish", "finish_timeout", "finish_timeout_raises", "save", "offline", "resumed", "grpc", "metric", "keras", "sagemaker", "artifact_incremental", "metaflow", "prodigy", "set_init_name", "set_init_id", "set_init_tags", "set_init_config", "set_run_name", "set_run_tags", "set_config_item", "launch", "torch_profiler_trace", "sb3", "init_return_run", "lightgbm_wandb_callback", "lightgbm_log_summary", "catboost_wandb_callback", "catboost_log_summary", "tensorboard_log", "estimator_hook", "xgboost_wandb_callback", "xgboost_old_wandb_callback", "attach", "tensorboard_patch", "tensorboard_sync", "kfp_wandb_log", "maybe_run_overwrite", "keras_metrics_logger", "keras_model_checkpoint", "keras_wandb_eval_callback", "flow_control_overflow", "sync", "flow_control_disabled", "flow_control_custom", "open_metrics", "ultralytics_yolov8", "importer_mlflow", "sync_tfevents", "async_uploads", "openai_autolog", "langchain_tracer", "cohere_autolog", "hf_pipeline_autolog", "lib_c", "lib_cpp", "openai_finetuning", "diffusers_autolog", "lightning_fabric_logger", "set_step_log", "set_summary", "metric_summary", "metric_goal", "metric_hidden", "metric_step_sync", "shared_mode", "server_side_derived_summary", "user_provided_label", "dcgm_profiling_enabled", "fork_mode", "rewind_mode", "dspy_callback"]
    WATCH_FIELD_NUMBER: _ClassVar[int]
    FINISH_FIELD_NUMBER: _ClassVar[int]
    FINISH_TIMEOUT_FIELD_NUMBER: _ClassVar[int]
    FINISH_TIMEOUT_RAISES_FIELD_NUMBER: _ClassVar[int]
    SAVE_FIELD_NUMBER: _ClassVar[int]
    OFFLINE_FIELD_NUMBER: _ClassVar[int]
    RESUMED_FIELD_NUMBER: _ClassVar[int]
    GRPC_FIELD_NUMBER: _ClassVar[int]
    METRIC_FIELD_NUMBER: _ClassVar[int]
    KERAS_FIELD_NUMBER: _ClassVar[int]
    SAGEMAKER_FIELD_NUMBER: _ClassVar[int]
    ARTIFACT_INCREMENTAL_FIELD_NUMBER: _ClassVar[int]
    METAFLOW_FIELD_NUMBER: _ClassVar[int]
    PRODIGY_FIELD_NUMBER: _ClassVar[int]
    SET_INIT_NAME_FIELD_NUMBER: _ClassVar[int]
    SET_INIT_ID_FIELD_NUMBER: _ClassVar[int]
    SET_INIT_TAGS_FIELD_NUMBER: _ClassVar[int]
    SET_INIT_CONFIG_FIELD_NUMBER: _ClassVar[int]
    SET_RUN_NAME_FIELD_NUMBER: _ClassVar[int]
    SET_RUN_TAGS_FIELD_NUMBER: _ClassVar[int]
    SET_CONFIG_ITEM_FIELD_NUMBER: _ClassVar[int]
    LAUNCH_FIELD_NUMBER: _ClassVar[int]
    TORCH_PROFILER_TRACE_FIELD_NUMBER: _ClassVar[int]
    SB3_FIELD_NUMBER: _ClassVar[int]
    INIT_RETURN_RUN_FIELD_NUMBER: _ClassVar[int]
    LIGHTGBM_WANDB_CALLBACK_FIELD_NUMBER: _ClassVar[int]
    LIGHTGBM_LOG_SUMMARY_FIELD_NUMBER: _ClassVar[int]
    CATBOOST_WANDB_CALLBACK_FIELD_NUMBER: _ClassVar[int]
    CATBOOST_LOG_SUMMARY_FIELD_NUMBER: _ClassVar[int]
    TENSORBOARD_LOG_FIELD_NUMBER: _ClassVar[int]
    ESTIMATOR_HOOK_FIELD_NUMBER: _ClassVar[int]
    XGBOOST_WANDB_CALLBACK_FIELD_NUMBER: _ClassVar[int]
    XGBOOST_OLD_WANDB_CALLBACK_FIELD_NUMBER: _ClassVar[int]
    ATTACH_FIELD_NUMBER: _ClassVar[int]
    TENSORBOARD_PATCH_FIELD_NUMBER: _ClassVar[int]
    TENSORBOARD_SYNC_FIELD_NUMBER: _ClassVar[int]
    KFP_WANDB_LOG_FIELD_NUMBER: _ClassVar[int]
    MAYBE_RUN_OVERWRITE_FIELD_NUMBER: _ClassVar[int]
    KERAS_METRICS_LOGGER_FIELD_NUMBER: _ClassVar[int]
    KERAS_MODEL_CHECKPOINT_FIELD_NUMBER: _ClassVar[int]
    KERAS_WANDB_EVAL_CALLBACK_FIELD_NUMBER: _ClassVar[int]
    FLOW_CONTROL_OVERFLOW_FIELD_NUMBER: _ClassVar[int]
    SYNC_FIELD_NUMBER: _ClassVar[int]
    FLOW_CONTROL_DISABLED_FIELD_NUMBER: _ClassVar[int]
    FLOW_CONTROL_CUSTOM_FIELD_NUMBER: _ClassVar[int]
    OPEN_METRICS_FIELD_NUMBER: _ClassVar[int]
    ULTRALYTICS_YOLOV8_FIELD_NUMBER: _ClassVar[int]
    IMPORTER_MLFLOW_FIELD_NUMBER: _ClassVar[int]
    SYNC_TFEVENTS_FIELD_NUMBER: _ClassVar[int]
    ASYNC_UPLOADS_FIELD_NUMBER: _ClassVar[int]
    OPENAI_AUTOLOG_FIELD_NUMBER: _ClassVar[int]
    LANGCHAIN_TRACER_FIELD_NUMBER: _ClassVar[int]
    COHERE_AUTOLOG_FIELD_NUMBER: _ClassVar[int]
    HF_PIPELINE_AUTOLOG_FIELD_NUMBER: _ClassVar[int]
    LIB_C_FIELD_NUMBER: _ClassVar[int]
    LIB_CPP_FIELD_NUMBER: _ClassVar[int]
    OPENAI_FINETUNING_FIELD_NUMBER: _ClassVar[int]
    DIFFUSERS_AUTOLOG_FIELD_NUMBER: _ClassVar[int]
    LIGHTNING_FABRIC_LOGGER_FIELD_NUMBER: _ClassVar[int]
    SET_STEP_LOG_FIELD_NUMBER: _ClassVar[int]
    SET_SUMMARY_FIELD_NUMBER: _ClassVar[int]
    METRIC_SUMMARY_FIELD_NUMBER: _ClassVar[int]
    METRIC_GOAL_FIELD_NUMBER: _ClassVar[int]
    METRIC_HIDDEN_FIELD_NUMBER: _ClassVar[int]
    METRIC_STEP_SYNC_FIELD_NUMBER: _ClassVar[int]
    SHARED_MODE_FIELD_NUMBER: _ClassVar[int]
    SERVER_SIDE_DERIVED_SUMMARY_FIELD_NUMBER: _ClassVar[int]
    USER_PROVIDED_LABEL_FIELD_NUMBER: _ClassVar[int]
    DCGM_PROFILING_ENABLED_FIELD_NUMBER: _ClassVar[int]
    FORK_MODE_FIELD_NUMBER: _ClassVar[int]
    REWIND_MODE_FIELD_NUMBER: _ClassVar[int]
    DSPY_CALLBACK_FIELD_NUMBER: _ClassVar[int]
    watch: bool
    finish: bool
    finish_timeout: bool
    finish_timeout_raises: bool
    save: bool
    offline: bool
    resumed: bool
    grpc: bool
    metric: bool
    keras: bool
    sagemaker: bool
    artifact_incremental: bool
    metaflow: bool
    prodigy: bool
    set_init_name: bool
    set_init_id: bool
    set_init_tags: bool
    set_init_config: bool
    set_run_name: bool
    set_run_tags: bool
    set_config_item: bool
    launch: bool
    torch_profiler_trace: bool
    sb3: bool
    init_return_run: bool
    lightgbm_wandb_callback: bool
    lightgbm_log_summary: bool
    catboost_wandb_callback: bool
    catboost_log_summary: bool
    tensorboard_log: bool
    estimator_hook: bool
    xgboost_wandb_callback: bool
    xgboost_old_wandb_callback: bool
    attach: bool
    tensorboard_patch: bool
    tensorboard_sync: bool
    kfp_wandb_log: bool
    maybe_run_overwrite: bool
    keras_metrics_logger: bool
    keras_model_checkpoint: bool
    keras_wandb_eval_callback: bool
    flow_control_overflow: bool
    sync: bool
    flow_control_disabled: bool
    flow_control_custom: bool
    open_metrics: bool
    ultralytics_yolov8: bool
    importer_mlflow: bool
    sync_tfevents: bool
    async_uploads: bool
    openai_autolog: bool
    langchain_tracer: bool
    cohere_autolog: bool
    hf_pipeline_autolog: bool
    lib_c: bool
    lib_cpp: bool
    openai_finetuning: bool
    diffusers_autolog: bool
    lightning_fabric_logger: bool
    set_step_log: bool
    set_summary: bool
    metric_summary: bool
    metric_goal: bool
    metric_hidden: bool
    metric_step_sync: bool
    shared_mode: bool
    server_side_derived_summary: bool
    user_provided_label: bool
    dcgm_profiling_enabled: bool
    fork_mode: bool
    rewind_mode: bool
    dspy_callback: bool
    def __init__(self, watch: bool = ..., finish: bool = ..., finish_timeout: bool = ..., finish_timeout_raises: bool = ..., save: bool = ..., offline: bool = ..., resumed: bool = ..., grpc: bool = ..., metric: bool = ..., keras: bool = ..., sagemaker: bool = ..., artifact_incremental: bool = ..., metaflow: bool = ..., prodigy: bool = ..., set_init_name: bool = ..., set_init_id: bool = ..., set_init_tags: bool = ..., set_init_config: bool = ..., set_run_name: bool = ..., set_run_tags: bool = ..., set_config_item: bool = ..., launch: bool = ..., torch_profiler_trace: bool = ..., sb3: bool = ..., init_return_run: bool = ..., lightgbm_wandb_callback: bool = ..., lightgbm_log_summary: bool = ..., catboost_wandb_callback: bool = ..., catboost_log_summary: bool = ..., tensorboard_log: bool = ..., estimator_hook: bool = ..., xgboost_wandb_callback: bool = ..., xgboost_old_wandb_callback: bool = ..., attach: bool = ..., tensorboard_patch: bool = ..., tensorboard_sync: bool = ..., kfp_wandb_log: bool = ..., maybe_run_overwrite: bool = ..., keras_metrics_logger: bool = ..., keras_model_checkpoint: bool = ..., keras_wandb_eval_callback: bool = ..., flow_control_overflow: bool = ..., sync: bool = ..., flow_control_disabled: bool = ..., flow_control_custom: bool = ..., open_metrics: bool = ..., ultralytics_yolov8: bool = ..., importer_mlflow: bool = ..., sync_tfevents: bool = ..., async_uploads: bool = ..., openai_autolog: bool = ..., langchain_tracer: bool = ..., cohere_autolog: bool = ..., hf_pipeline_autolog: bool = ..., lib_c: bool = ..., lib_cpp: bool = ..., openai_finetuning: bool = ..., diffusers_autolog: bool = ..., lightning_fabric_logger: bool = ..., set_step_log: bool = ..., set_summary: bool = ..., metric_summary: bool = ..., metric_goal: bool = ..., metric_hidden: bool = ..., metric_step_sync: bool = ..., shared_mode: bool = ..., server_side_derived_summary: bool = ..., user_provided_label: bool = ..., dcgm_profiling_enabled: bool = ..., fork_mode: bool = ..., rewind_mode: bool = ..., dspy_callback: bool = ...) -> None: ...

class Env(_message.Message):
    __slots__ = ["jupyter", "kaggle", "windows", "m1_gpu", "trainium", "pex", "colab", "ipython", "aws_lambda", "amd_gpu"]
    JUPYTER_FIELD_NUMBER: _ClassVar[int]
    KAGGLE_FIELD_NUMBER: _ClassVar[int]
    WINDOWS_FIELD_NUMBER: _ClassVar[int]
    M1_GPU_FIELD_NUMBER: _ClassVar[int]
    TRAINIUM_FIELD_NUMBER: _ClassVar[int]
    PEX_FIELD_NUMBER: _ClassVar[int]
    COLAB_FIELD_NUMBER: _ClassVar[int]
    IPYTHON_FIELD_NUMBER: _ClassVar[int]
    AWS_LAMBDA_FIELD_NUMBER: _ClassVar[int]
    AMD_GPU_FIELD_NUMBER: _ClassVar[int]
    jupyter: bool
    kaggle: bool
    windows: bool
    m1_gpu: bool
    trainium: bool
    pex: bool
    colab: bool
    ipython: bool
    aws_lambda: bool
    amd_gpu: bool
    def __init__(self, jupyter: bool = ..., kaggle: bool = ..., windows: bool = ..., m1_gpu: bool = ..., trainium: bool = ..., pex: bool = ..., colab: bool = ..., ipython: bool = ..., aws_lambda: bool = ..., amd_gpu: bool = ...) -> None: ...

class Labels(_message.Message):
    __slots__ = ["code_string", "repo_string", "code_version"]
    CODE_STRING_FIELD_NUMBER: _ClassVar[int]
    REPO_STRING_FIELD_NUMBER: _ClassVar[int]
    CODE_VERSION_FIELD_NUMBER: _ClassVar[int]
    code_string: str
    repo_string: str
    code_version: str
    def __init__(self, code_string: _Optional[str] = ..., repo_string: _Optional[str] = ..., code_version: _Optional[str] = ...) -> None: ...

class Deprecated(_message.Message):
    __slots__ = ["keras_callback__data_type", "plots", "init__config_include_keys", "init__config_exclude_keys", "keras_callback__save_model", "langchain_tracer", "artifact__get_path", "artifactmanifestentry__name", "api__artifact_versions", "artifact_collection__change_type", "run__define_metric_copy", "run_disabled", "keras_callback", "run__define_metric_best_goal", "run__finish_quiet", "run__reinit_bool", "run__get_url", "run__project_name", "run__get_project_url", "run__get_sweep_url", "run__use_artifact_use_as", "artifact__use_as", "artifact__init_use_as", "beta__workflows__log_model", "beta__workflows__use_model", "beta__workflows__link_model", "kfp_v1_wandb_log"]
    KERAS_CALLBACK__DATA_TYPE_FIELD_NUMBER: _ClassVar[int]
    PLOTS_FIELD_NUMBER: _ClassVar[int]
    INIT__CONFIG_INCLUDE_KEYS_FIELD_NUMBER: _ClassVar[int]
    INIT__CONFIG_EXCLUDE_KEYS_FIELD_NUMBER: _ClassVar[int]
    KERAS_CALLBACK__SAVE_MODEL_FIELD_NUMBER: _ClassVar[int]
    LANGCHAIN_TRACER_FIELD_NUMBER: _ClassVar[int]
    ARTIFACT__GET_PATH_FIELD_NUMBER: _ClassVar[int]
    ARTIFACTMANIFESTENTRY__NAME_FIELD_NUMBER: _ClassVar[int]
    API__ARTIFACT_VERSIONS_FIELD_NUMBER: _ClassVar[int]
    ARTIFACT_COLLECTION__CHANGE_TYPE_FIELD_NUMBER: _ClassVar[int]
    RUN__DEFINE_METRIC_COPY_FIELD_NUMBER: _ClassVar[int]
    RUN_DISABLED_FIELD_NUMBER: _ClassVar[int]
    KERAS_CALLBACK_FIELD_NUMBER: _ClassVar[int]
    RUN__DEFINE_METRIC_BEST_GOAL_FIELD_NUMBER: _ClassVar[int]
    RUN__FINISH_QUIET_FIELD_NUMBER: _ClassVar[int]
    RUN__REINIT_BOOL_FIELD_NUMBER: _ClassVar[int]
    RUN__GET_URL_FIELD_NUMBER: _ClassVar[int]
    RUN__PROJECT_NAME_FIELD_NUMBER: _ClassVar[int]
    RUN__GET_PROJECT_URL_FIELD_NUMBER: _ClassVar[int]
    RUN__GET_SWEEP_URL_FIELD_NUMBER: _ClassVar[int]
    RUN__USE_ARTIFACT_USE_AS_FIELD_NUMBER: _ClassVar[int]
    ARTIFACT__USE_AS_FIELD_NUMBER: _ClassVar[int]
    ARTIFACT__INIT_USE_AS_FIELD_NUMBER: _ClassVar[int]
    BETA__WORKFLOWS__LOG_MODEL_FIELD_NUMBER: _ClassVar[int]
    BETA__WORKFLOWS__USE_MODEL_FIELD_NUMBER: _ClassVar[int]
    BETA__WORKFLOWS__LINK_MODEL_FIELD_NUMBER: _ClassVar[int]
    KFP_V1_WANDB_LOG_FIELD_NUMBER: _ClassVar[int]
    keras_callback__data_type: bool
    plots: bool
    init__config_include_keys: bool
    init__config_exclude_keys: bool
    keras_callback__save_model: bool
    langchain_tracer: bool
    artifact__get_path: bool
    artifactmanifestentry__name: bool
    api__artifact_versions: bool
    artifact_collection__change_type: bool
    run__define_metric_copy: bool
    run_disabled: bool
    keras_callback: bool
    run__define_metric_best_goal: bool
    run__finish_quiet: bool
    run__reinit_bool: bool
    run__get_url: bool
    run__project_name: bool
    run__get_project_url: bool
    run__get_sweep_url: bool
    run__use_artifact_use_as: bool
    artifact__use_as: bool
    artifact__init_use_as: bool
    beta__workflows__log_model: bool
    beta__workflows__use_model: bool
    beta__workflows__link_model: bool
    kfp_v1_wandb_log: bool
    def __init__(self, keras_callback__data_type: bool = ..., plots: bool = ..., init__config_include_keys: bool = ..., init__config_exclude_keys: bool = ..., keras_callback__save_model: bool = ..., langchain_tracer: bool = ..., artifact__get_path: bool = ..., artifactmanifestentry__name: bool = ..., api__artifact_versions: bool = ..., artifact_collection__change_type: bool = ..., run__define_metric_copy: bool = ..., run_disabled: bool = ..., keras_callback: bool = ..., run__define_metric_best_goal: bool = ..., run__finish_quiet: bool = ..., run__reinit_bool: bool = ..., run__get_url: bool = ..., run__project_name: bool = ..., run__get_project_url: bool = ..., run__get_sweep_url: bool = ..., run__use_artifact_use_as: bool = ..., artifact__use_as: bool = ..., artifact__init_use_as: bool = ..., beta__workflows__log_model: bool = ..., beta__workflows__use_model: bool = ..., beta__workflows__link_model: bool = ..., kfp_v1_wandb_log: bool = ...) -> None: ...

class Issues(_message.Message):
    __slots__ = ["settings__validation_warnings", "settings__unexpected_args", "settings__preprocessing_warnings"]
    SETTINGS__VALIDATION_WARNINGS_FIELD_NUMBER: _ClassVar[int]
    SETTINGS__UNEXPECTED_ARGS_FIELD_NUMBER: _ClassVar[int]
    SETTINGS__PREPROCESSING_WARNINGS_FIELD_NUMBER: _ClassVar[int]
    settings__validation_warnings: bool
    settings__unexpected_args: bool
    settings__preprocessing_warnings: bool
    def __init__(self, settings__validation_warnings: bool = ..., settings__unexpected_args: bool = ..., settings__preprocessing_warnings: bool = ...) -> None: ...
