// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: wandb/proto/wandb_system_monitor.proto

package service_go_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Seconds between the samples delivered to this subscriber, 0.1 or more.
	//
	// The service samples the hardware once for all of its subscribers and may
	// sample more often than this to serve a subscriber with a shorter interval.
	// Metrics that describe the time since the previous sample, such as GPM
	// utilization, are averaged over this interval.
	IntervalSeconds float64 `protobuf:"fixed64,1,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"`
	// Capture the system metrics for the process with this PID, in addition to
	// system-wide metrics.
	Pid int32 `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	// GPU device IDs to capture metrics for.
	//
	// Should be 0-indexed and match those reported by the CUDA/ROCm runtime environment.
	// If not set, metrics for all GPUs will be captured.
	GpuDeviceIds  []int32 `protobuf:"varint,3,rep,packed,name=gpu_device_ids,json=gpuDeviceIds,proto3" json:"gpu_device_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_wandb_proto_wandb_system_monitor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wandb_proto_wandb_system_monitor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_wandb_proto_wandb_system_monitor_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequest) GetIntervalSeconds() float64 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

func (x *SubscribeRequest) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *SubscribeRequest) GetGpuDeviceIds() []int32 {
	if x != nil {
		return x.GpuDeviceIds
	}
	return nil
}

type SubscribeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// System metrics.
	Record        *Record `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	mi := &file_wandb_proto_wandb_system_monitor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wandb_proto_wandb_system_monitor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponse.ProtoReflect.Descriptor instead.
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return file_wandb_proto_wandb_system_monitor_proto_rawDescGZIP(), []int{1}
}

func (x *SubscribeResponse) GetRecord() *Record {
	if x != nil {
		return x.Record
	}
	return nil
}

type GetMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetadataRequest) Reset() {
	*x = GetMetadataRequest{}
	mi := &file_wandb_proto_wandb_system_monitor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetadataRequest) ProtoMessage() {}

func (x *GetMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wandb_proto_wandb_system_monitor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetMetadataRequest) Descriptor() ([]byte, []int) {
	return file_wandb_proto_wandb_system_monitor_proto_rawDescGZIP(), []int{2}
}

type GetMetadataResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Static metadata about the system.
	Record        *Record `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetadataResponse) Reset() {
	*x = GetMetadataResponse{}
	mi := &file_wandb_proto_wandb_system_monitor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetadataResponse) ProtoMessage() {}

func (x *GetMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wandb_proto_wandb_system_monitor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetadataResponse.ProtoReflect.Descriptor instead.
func (*GetMetadataResponse) Descriptor() ([]byte, []int) {
	return file_wandb_proto_wandb_system_monitor_proto_rawDescGZIP(), []int{3}
}

func (x *GetMetadataResponse) GetRecord() *Record {
	if x != nil {
		return x.Record
	}
	return nil
}

type TearDownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TearDownRequest) Reset() {
	*x = TearDownRequest{}
	mi := &file_wandb_proto_wandb_system_monitor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TearDownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TearDownRequest) ProtoMessage() {}

func (x *TearDownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wandb_proto_wandb_system_monitor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TearDownRequest.ProtoReflect.Descriptor instead.
func (*TearDownRequest) Descriptor() ([]byte, []int) {
	return file_wandb_proto_wandb_system_monitor_proto_rawDescGZIP(), []int{4}
}

type TearDownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TearDownResponse) Reset() {
	*x = TearDownResponse{}
	mi := &file_wandb_proto_wandb_system_monitor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TearDownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TearDownResponse) ProtoMessage() {}

func (x *TearDownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wandb_proto_wandb_system_monitor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TearDownResponse.ProtoReflect.Descriptor instead.
func (*TearDownResponse) Descriptor() ([]byte, []int) {
	return file_wandb_proto_wandb_system_monitor_proto_rawDescGZIP(), []int{5}
}

var File_wandb_proto_wandb_system_monitor_proto protoreflect.FileDescriptor

const file_wandb_proto_wandb_system_monitor_proto_rawDesc = "" +
	"\n" +
	"&wandb/proto/wandb_system_monitor.proto\x12\x0ewandb_internal\x1a wandb/proto/wandb_internal.proto\"u\n" +
	"\x10SubscribeRequest\x12)\n" +
	"\x10interval_seconds\x18\x01 \x01(\x01R\x0fintervalSeconds\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x05R\x03pid\x12$\n" +
	"\x0egpu_device_ids\x18\x03 \x03(\x05R\fgpuDeviceIds\"C\n" +
	"\x11SubscribeResponse\x12.\n" +
	"\x06record\x18\x01 \x01(\v2\x16.wandb_internal.RecordR\x06record\"\x14\n" +
	"\x12GetMetadataRequest\"E\n" +
	"\x13GetMetadataResponse\x12.\n" +
	"\x06record\x18\x01 \x01(\v2\x16.wandb_internal.RecordR\x06record\"\x11\n" +
	"\x0fTearDownRequest\"\x12\n" +
	"\x10TearDownResponse2\x97\x02\n" +
	"\x14SystemMonitorService\x12T\n" +
	"\tSubscribe\x12 .wandb_internal.SubscribeRequest\x1a!.wandb_internal.SubscribeResponse\"\x000\x01\x12X\n" +
	"\vGetMetadata\x12\".wandb_internal.GetMetadataRequest\x1a#.wandb_internal.GetMetadataResponse\"\x00\x12O\n" +
	"\bTearDown\x12\x1f.wandb_internal.TearDownRequest\x1a .wandb_internal.TearDownResponse\"\x00B\x1bZ\x19core/pkg/service_go_protob\x06proto3"

var (
	file_wandb_proto_wandb_system_monitor_proto_rawDescOnce sync.Once
	file_wandb_proto_wandb_system_monitor_proto_rawDescData []byte
)

func file_wandb_proto_wandb_system_monitor_proto_rawDescGZIP() []byte {
	file_wandb_proto_wandb_system_monitor_proto_rawDescOnce.Do(func() {
		file_wandb_proto_wandb_system_monitor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wandb_proto_wandb_system_monitor_proto_rawDesc), len(file_wandb_proto_wandb_system_monitor_proto_rawDesc)))
	})
	return file_wandb_proto_wandb_system_monitor_proto_rawDescData
}

var file_wandb_proto_wandb_system_monitor_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_wandb_proto_wandb_system_monitor_proto_goTypes = []any{
	(*SubscribeRequest)(nil),    // 0: wandb_internal.SubscribeRequest
	(*SubscribeResponse)(nil),   // 1: wandb_internal.SubscribeResponse
	(*GetMetadataRequest)(nil),  // 2: wandb_internal.GetMetadataRequest
	(*GetMetadataResponse)(nil), // 3: wandb_internal.GetMetadataResponse
	(*TearDownRequest)(nil),     // 4: wandb_internal.TearDownRequest
	(*TearDownResponse)(nil),    // 5: wandb_internal.TearDownResponse
	(*Record)(nil),              // 6: wandb_internal.Record
}
var file_wandb_proto_wandb_system_monitor_proto_depIdxs = []int32{
	6, // 0: wandb_internal.SubscribeResponse.record:type_name -> wandb_internal.Record
	6, // 1: wandb_internal.GetMetadataResponse.record:type_name -> wandb_internal.Record
	0, // 2: wandb_internal.SystemMonitorService.Subscribe:input_type -> wandb_internal.SubscribeRequest
	2, // 3: wandb_internal.SystemMonitorService.GetMetadata:input_type -> wandb_internal.GetMetadataRequest
	4, // 4: wandb_internal.SystemMonitorService.TearDown:input_type -> wandb_internal.TearDownRequest
	1, // 5: wandb_internal.SystemMonitorService.Subscribe:output_type -> wandb_internal.SubscribeResponse
	3, // 6: wandb_internal.SystemMonitorService.GetMetadata:output_type -> wandb_internal.GetMetadataResponse
	5, // 7: wandb_internal.SystemMonitorService.TearDown:output_type -> wandb_internal.TearDownResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_wandb_proto_wandb_system_monitor_proto_init() }
func file_wandb_proto_wandb_system_monitor_proto_init() {
	if File_wandb_proto_wandb_system_monitor_proto != nil {
		return
	}
	file_wandb_proto_wandb_internal_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wandb_proto_wandb_system_monitor_proto_rawDesc), len(file_wandb_proto_wandb_system_monitor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wandb_proto_wandb_system_monitor_proto_goTypes,
		DependencyIndexes: file_wandb_proto_wandb_system_monitor_proto_depIdxs,
		MessageInfos:      file_wandb_proto_wandb_system_monitor_proto_msgTypes,
	}.Build()
	File_wandb_proto_wandb_system_monitor_proto = out.File
	file_wandb_proto_wandb_system_monitor_proto_goTypes = nil
	file_wandb_proto_wandb_system_monitor_proto_depIdxs = nil
}
