package ffi

import (
	"cmp"
	"encoding/base64"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/wandb/wandb/core/internal/runhistoryreader/parquet"
)

// These fixtures use the schema that Gorilla writes: nullable Float64 _step,
// nullable metrics, a nullable struct, and an unrelated column.
const lateStepFixture = `
UEFSMRUEFSAVIEwVBBUAEgAAAAAAAAAANEAAAAAAAAA1QBUAFRIVEiwVBBUQFQYVBhw2ACgIAAAAAAAANUAYCAAAAAAAADRAEREA
AAACAAAABAEBAwIVBBUQFRBMFQIVABIAAAAAAAAAACRAFQAVEBUQLBUEFRAVBhUGHDYCKAgAAAAAAAAkQBgIAAAAAAAAJEAREQAA
AAIAAAADAQACFQQVEBUQTBUCFQASAAAAAAAAAADwPxUAFRIVEiwVBBUQFQYVBhw2AigIAAAAAAAA8D8YCAAAAAAAAPA/EREAAAAD
AAAAAwYAAAIVBBUKFQpMFQIVABIAAAEAAABhFQAVEhUSLBUEFRAVBhUGHDYCKAFhGAFhEREAAAADAAAAAwYAAAIVBBUoFShMFQQV
ABIAAAYAAABvbWl0LWEGAAAAb21pdC1iFQAVEhUSLBUEFRAVBhUGHDYAKAZvbWl0LWIYBm9taXQtYRERAAAAAgAAAAQBAQMCGREC
GRgIAAAAAAAANEAZGAgAAAAAAAA1QBUCGRYAKSYABAAZEQIZGAgAAAAAAAAkQBkYCAAAAAAAACRAFQIZFgIpJgICABkRAhkYCAAA
AAAAAPA/GRgIAAAAAAAA8D8VAhkWAik2AAICABkRAhkYAWEZGAFhFQIZFgIpNgACAgAZEQIZGAZvbWl0LWEZGAZvbWl0LWIVAhkW
ACkmAAQAGRwWRBVoFgAAABkcFtgBFWYWAAAAGRwW6gIVaBYAAAAZHBb4AxVMFgAAGRYCABkcFogFFWAWAAAZFhgAFQIZfEgMYXJy
b3dfc2NoZW1hFQgAFQolAhgFX3N0ZXAAFQolAhgLZmxhdF9tZXRyaWMANQIYBm5lc3RlZBUEABUKJQIYBXNjb3JlABUMJQIYBWxh
YmVsJQBMHAAAABUMJQIYCXVucmVsYXRlZCUATBwAAAAWBBkcGVwmABwVChk1AAYQGRgFX3N0ZXAVABYEFqQBFqQBJkQmCBwYCAAA
AAAAADVAGAgAAAAAAAA0QBYAKAgAAAAAAAA1QBgIAAAAAAAANEAREQBMOSYABAAAFqYIFRQW6AUVRgAmABwVChk1AAYQGRgLZmxh
dF9tZXRyaWMVABYEFpIBFpIBJtgBJqwBHBgIAAAAAAAAJEAYCAAAAAAAACRAFgIoCAAAAAAAACRAGAgAAAAAAAAkQBERAEw5JgIC
AAAWuggVFhauBhVGACYAHBUKGTUABhAZKAZuZXN0ZWQFc2NvcmUVABYEFpQBFpQBJuoCJr4CHBgIAAAAAAAA8D8YCAAAAAAAAPA/
FgIoCAAAAAAAAPA/GAgAAAAAAADwPxERAEw5NgACAgAAFtAIFRYW9AYVSAAmABwVDBk1AAYQGSgGbmVzdGVkBWxhYmVsFQAWBBZy
FnIm+AMm0gMcNgIoAWEYAWEREQBMFgIpNgACAgAAFuYIFRwWvAcVLAAmABwVDBk1AAYQGRgJdW5yZWxhdGVkFQAWBBakARakASaI
BSbEBBw2ACgGb21pdC1iGAZvbWl0LWEREQBMFhgpJgAEAAAWggkVHBboBxU+ABbgBRYEJggW4AUUAAAZHBgMQVJST1c6c2NoZW1h
GIAELy8vLy8zZ0JBQUFRQUFBQUFBQUtBQXdBQ2dBSkFBUUFDZ0FBQUJBQUFBQUFBUVFBQ0FBSUFBQUFCQUFJQUFBQUJBQUFBQVFB
QUFBVUFRQUEwQUFBQURRQUFBQUVBQUFBVFAvLy94UUFBQUFNQUFBQUFBQUJCUXdBQUFBQUFBQUFzUC8vL3drQUFBQjFibkpsYkdG
MFpXUUFBQUI0Ly8vL0hBQUFBQXdBQUFBQUFBRU5iQUFBQUFJQUFBQTRBQUFBQ0FBQUFPVC8vLytjLy8vL0dBQUFBQXdBQUFBQUFB
RUZFQUFBQUFBQUFBQUVBQVFBQkFBQUFBVUFBQUJzWVdKbGJBQUFBTWovLy84UUFBQUFGQUFBQUFBQUFRTVFBQUFBZHYvLy93QUFB
Z0FBQUFBQUJRQUFBSE5qYjNKbEFBQUFCZ0FBQUc1bGMzUmxaQUFBRUFBVUFCQUFEZ0FQQUFRQUFBQUlBQkFBQUFBUUFBQUFGQUFB
QUFBQUFRTVFBQUFBdnYvLy93QUFBZ0FBQUFBQUN3QUFBR1pzWVhSZmJXVjBjbWxqQUJBQUZnQVFBQTRBRHdBRUFBQUFDQUFRQUFB
QUdBQUFBQndBQUFBQUFBRURHQUFBQUFBQUJnQUlBQVlBQmdBQUFBQUFBZ0FBQUFBQUJRQUFBRjl6ZEdWd0FBQUEAGBlwYXJxdWV0
LXJzIHZlcnNpb24gNTMuNC4xGVwcAAAcAAAcAAAcAAAcAAAAkgQAAFBBUjE=
`

const earlyStepFixture = `
UEFSMRUEFSAVIEwVBBUAEgAAAAAAAAAAFEAAAAAAAAAYQBUAFRIVEiwVBBUQFQYVBhw2ACgIAAAAAAAAGEAYCAAAAAAAABRAEREA
AAACAAAABAEBAwIVBBUQFRBMFQIVABIAAAAAAAAAACRAFQAVEBUQLBUEFRAVBhUGHDYCKAgAAAAAAAAkQBgIAAAAAAAAJEAREQAA
AAIAAAADAQACFQQVEBUQTBUCFQASAAAAAAAAAADwPxUAFRIVEiwVBBUQFQYVBhw2AigIAAAAAAAA8D8YCAAAAAAAAPA/EREAAAAD
AAAAAwYAAAIVBBUKFQpMFQIVABIAAAEAAABhFQAVEhUSLBUEFRAVBhUGHDYCKAFhGAFhEREAAAADAAAAAwYAAAIVBBUoFShMFQQV
ABIAAAYAAABvbWl0LWEGAAAAb21pdC1iFQAVEhUSLBUEFRAVBhUGHDYAKAZvbWl0LWIYBm9taXQtYRERAAAAAgAAAAQBAQMCGREC
GRgIAAAAAAAAFEAZGAgAAAAAAAAYQBUCGRYAKSYABAAZEQIZGAgAAAAAAAAkQBkYCAAAAAAAACRAFQIZFgIpJgICABkRAhkYCAAA
AAAAAPA/GRgIAAAAAAAA8D8VAhkWAik2AAICABkRAhkYAWEZGAFhFQIZFgIpNgACAgAZEQIZGAZvbWl0LWEZGAZvbWl0LWIVAhkW
ACkmAAQAGRwWRBVoFgAAABkcFtgBFWYWAAAAGRwW6gIVaBYAAAAZHBb4AxVMFgAAGRYCABkcFogFFWAWAAAZFhgAFQIZfEgMYXJy
b3dfc2NoZW1hFQgAFQolAhgFX3N0ZXAAFQolAhgLZmxhdF9tZXRyaWMANQIYBm5lc3RlZBUEABUKJQIYBXNjb3JlABUMJQIYBWxh
YmVsJQBMHAAAABUMJQIYCXVucmVsYXRlZCUATBwAAAAWBBkcGVwmABwVChk1AAYQGRgFX3N0ZXAVABYEFqQBFqQBJkQmCBwYCAAA
AAAAABhAGAgAAAAAAAAUQBYAKAgAAAAAAAAYQBgIAAAAAAAAFEAREQBMOSYABAAAFqYIFRQW6AUVRgAmABwVChk1AAYQGRgLZmxh
dF9tZXRyaWMVABYEFpIBFpIBJtgBJqwBHBgIAAAAAAAAJEAYCAAAAAAAACRAFgIoCAAAAAAAACRAGAgAAAAAAAAkQBERAEw5JgIC
AAAWuggVFhauBhVGACYAHBUKGTUABhAZKAZuZXN0ZWQFc2NvcmUVABYEFpQBFpQBJuoCJr4CHBgIAAAAAAAA8D8YCAAAAAAAAPA/
FgIoCAAAAAAAAPA/GAgAAAAAAADwPxERAEw5NgACAgAAFtAIFRYW9AYVSAAmABwVDBk1AAYQGSgGbmVzdGVkBWxhYmVsFQAWBBZy
FnIm+AMm0gMcNgIoAWEYAWEREQBMFgIpNgACAgAAFuYIFRwWvAcVLAAmABwVDBk1AAYQGRgJdW5yZWxhdGVkFQAWBBakARakASaI
BSbEBBw2ACgGb21pdC1iGAZvbWl0LWEREQBMFhgpJgAEAAAWggkVHBboBxU+ABbgBRYEJggW4AUUAAAZHBgMQVJST1c6c2NoZW1h
GIAELy8vLy8zZ0JBQUFRQUFBQUFBQUtBQXdBQ2dBSkFBUUFDZ0FBQUJBQUFBQUFBUVFBQ0FBSUFBQUFCQUFJQUFBQUJBQUFBQVFB
QUFBVUFRQUEwQUFBQURRQUFBQUVBQUFBVFAvLy94UUFBQUFNQUFBQUFBQUJCUXdBQUFBQUFBQUFzUC8vL3drQUFBQjFibkpsYkdG
MFpXUUFBQUI0Ly8vL0hBQUFBQXdBQUFBQUFBRU5iQUFBQUFJQUFBQTRBQUFBQ0FBQUFPVC8vLytjLy8vL0dBQUFBQXdBQUFBQUFB
RUZFQUFBQUFBQUFBQUVBQVFBQkFBQUFBVUFBQUJzWVdKbGJBQUFBTWovLy84UUFBQUFGQUFBQUFBQUFRTVFBQUFBZHYvLy93QUFB
Z0FBQUFBQUJRQUFBSE5qYjNKbEFBQUFCZ0FBQUc1bGMzUmxaQUFBRUFBVUFCQUFEZ0FQQUFRQUFBQUlBQkFBQUFBUUFBQUFGQUFB
QUFBQUFRTVFBQUFBdnYvLy93QUFBZ0FBQUFBQUN3QUFBR1pzWVhSZmJXVjBjbWxqQUJBQUZnQVFBQTRBRHdBRUFBQUFDQUFRQUFB
QUdBQUFBQndBQUFBQUFBRURHQUFBQUFBQUJnQUlBQVlBQmdBQUFBQUFBZ0FBQUFBQUJRQUFBRjl6ZEdWd0FBQUEAGBlwYXJxdWV0
LXJzIHZlcnNpb24gNTMuNC4xGVwcAAAcAAAcAAAcAAAcAAAAkgQAAFBBUjE=
`

const (
	requireRustArrowLibraryEnv = "WANDB_TEST_REQUIRE_RUST_ARROW_LIBRARY"
	rustArrowLibraryEnv        = "WANDB_TEST_RUST_ARROW_LIBRARY"
)

func TestRustArrowReaderProjectsNestedFieldsAndNormalizesSteps(t *testing.T) {
	libraryPath := rustArrowLibraryPath(t)

	wrapper, err := newRustArrowWrapper(libraryPath)
	require.NoError(t, err)

	fixtures := []string{
		writeParquetFixture(t, "late.parquet", lateStepFixture),
		writeParquetFixture(t, "early.parquet", earlyStepFixture),
	}
	var rows []parquet.KeyValueList
	for _, fixture := range fixtures {
		reader, err := CreateRustArrowReader(
			wrapper,
			fixture,
			[]string{parquet.StepKey, "flat_metric", "nested"},
		)
		require.NoError(t, err)
		t.Cleanup(reader.Release)

		partitionRows, err := reader.ScanStepRange(t.Context(), 0, 100)
		require.NoError(t, err)
		rows = append(rows, partitionRows...)
	}

	require.Equal(t, []int64{20, 21, 5, 6}, stepValues(rows))
	for _, row := range rows {
		require.Equal(
			t,
			[]string{parquet.StepKey, "flat_metric", "nested"},
			rowKeys(row),
		)

		values := rowValues(row)
		require.NotContains(t, values, "unrelated")
		nested, ok := values["nested"].(map[string]any)
		require.True(t, ok)
		require.Len(t, nested, 2)
		require.Contains(t, nested, "score")
		require.Contains(t, nested, "label")

		for _, pair := range row {
			if pair.Key == parquet.StepKey {
				require.IsType(t, int64(0), pair.Value)
			}
		}
	}

	slices.SortFunc(rows, func(a, b parquet.KeyValueList) int {
		return cmp.Compare(a.StepValue(), b.StepValue())
	})
	require.Equal(t, []int64{5, 6, 20, 21}, stepValues(rows))
}

func rustArrowLibraryPath(t *testing.T) string {
	t.Helper()

	libraryPath := os.Getenv(rustArrowLibraryEnv)
	if libraryPath != "" {
		return libraryPath
	}

	if os.Getenv(requireRustArrowLibraryEnv) == "1" {
		t.Fatalf(
			"%s=1 requires %s to name the Rust dynamic library",
			requireRustArrowLibraryEnv,
			rustArrowLibraryEnv,
		)
	}

	t.Skipf("set %s to run the Rust FFI integration test", rustArrowLibraryEnv)
	return ""
}

func writeParquetFixture(t *testing.T, name string, encoded string) string {
	t.Helper()

	data, err := base64.StdEncoding.DecodeString(strings.Join(strings.Fields(encoded), ""))
	require.NoError(t, err)
	path := filepath.Join(t.TempDir(), name)
	require.NoError(t, os.WriteFile(path, data, 0o600))
	return path
}

func stepValues(rows []parquet.KeyValueList) []int64 {
	steps := make([]int64, len(rows))
	for i, row := range rows {
		steps[i] = row.StepValue()
	}
	return steps
}

func rowKeys(row parquet.KeyValueList) []string {
	keys := make([]string, len(row))
	for i, pair := range row {
		keys[i] = pair.Key
	}
	return keys
}

func rowValues(row parquet.KeyValueList) map[string]any {
	values := make(map[string]any, len(row))
	for _, pair := range row {
		values[pair.Key] = pair.Value
	}
	return values
}
