changelog:
  exclude:
    labels:
      - changelog-ignore
      - ignore-for-release
      - cc-revert
    authors:
      - octocat
  categories:
    - title: ":magic_wand: Enhancements"
      labels:
        - cc-feat
        - cc-perf
    - title: ":hammer: Fixes"
      labels:
        - cc-fix
        - cc-security
    - title: ":books: Docs"
      labels:
        - cc-docs
    - title: ":gear: Dev"
      labels:
        - cc-build
        - cc-ci
        - cc-test
        - cc-chore
    - title: ":nail_care: Cleanup"
      labels:
        - "*"
