changelog:
  exclude:
    labels:
      - changelog-ignore
      - ignore-for-release
      - cc-revert
      - cc-build
      - cc-ci
      - cc-test
      - cc-chore
      - cc-refactor
      - cc-docs
    authors:
      - octocat
  categories:
    - title: ":magic_wand: Enhancements"
      labels:
        - cc-feat
        - cc-perf
    - title: ":hammer: Fixes"
      labels:
        - cc-fix
        - cc-security
    - title: ":nail_care: Cleanup"
      labels:
        - "*"
