codecov:
  require_ci_to_pass: yes

flags:
  sdk:
    paths:
      - wandb/sdk/*.py
  other:
    paths:
      - "!wandb/sdk/*.py"
      - wandb/
  tests:
    paths:
      - tests/
coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    patch:
      sdk:
        target: auto
        paths:
          - wandb/sdk/*.py
        flags:
          - sdk
      other:
        informational: true
        target: auto
        flags:
          - other
      tests:
        target: 100%
        flags:
          - tests

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
