codecov:
  require_ci_to_pass: no
  notify:
    wait_for_ci: yes

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: no

ignore:
  # Ignore all vendored files.
  - "wandb/vendor"
  - "core/vendor"

  # Ignore all generated proto files.
  - "**/*.pb.go"
  - "**/*_pb2.py"
  - "**/*_pb2.pyi"

  # Ignore generated GraphQL files.
  - "core/internal/gql"

  # Specific scripts and generated files that should be ignored.
  - "wandb/proto/wandb_deprecated.py"
  - "wandb/proto/wandb_generate_deprecated.py"
  - "wandb/proto/wandb_generate_proto.py"

coverage:
  precision: 2
  round: down
  range: "50...100"
  status:
    project:
      default:
        threshold: 0.75%
        if_ci_failed: error #success, failure, error, ignore
    patch:
      default:
        target: 0
        informational: true
      sdk:
        paths:
          - wandb/sdk/*.py
      sdk-internal:
        paths:
          - wandb/sdk/internal/
      sdk-launch:
        paths:
          - wandb/sdk/launch/
      sdk-service:
        paths:
          - wandb/sdk/service/
      sdk-other:
        paths:
          - "!wandb/sdk/*.py"
          - "!wandb/sdk/internal/"
          - "!wandb/sdk/launch/"
          - "!wandb/sdk/service/"
          - wandb/sdk/
      apis:
        informational: true
        paths:
          - wandb/apis/
      core:
        paths:
          - core/
      other:
        informational: true
        paths:
          - "!wandb/sdk/"
          - "!wandb/apis/"
          - wandb/

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

github_checks:
  annotations: true
