codecov:
  require_ci_to_pass: no
  notify:
    # after_n_builds calculation
    # 6 = 1 (lin-py36) + 4 (win-py37) + 1 (func-lin-py37)
    # also change comment section
    after_n_builds: 6
    wait_for_ci: no

ignore:
  - "wandb/vendor"

coverage:
  precision: 2
  round: down
  range: "50...100"
  status:
    project:
      default:
        threshold: 0.75%
    patch:
      sdk:
        paths:
          - wandb/sdk/*.py
      sdk-internal:
        paths:
          - wandb/sdk/internal/
      sdk-other:
        paths:
          - "!wandb/sdk/*.py"
          - "!wandb/sdk/internal/"
          - wandb/sdk/
      apis:
        informational: true
        paths:
          - wandb/apis/
      other:
        informational: true
        paths:
          - "!wandb/sdk/"
          - "!wandb/apis/"
          - wandb/

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: no
  after_n_builds: 6
 
github_checks:
  annotations: true
