[pytest]
markers =
    image_output
    multiclass
    wandb_args
    flaky: tests marked as flaky need to be debugged
testpaths = tests
timeout = 60
filterwarnings =
    ignore::DeprecationWarning

log_format = %(asctime)s %(levelname)s %(message)s
log_date_format = %Y-%m-%d %H:%M:%S
