apiVersion: v1
kind: Namespace
metadata:
  name: wandb
  labels:
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/warn: baseline
    pod-security.kubernetes.io/warn-version: latest
---
# role for handling builds and jobs within the wandb namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: wandb
  name: wandb-launch-agent
rules:
- apiGroups: [""]
  resources: ["pods", "configmaps", "secrets", "pods/log"]
  verbs: ["create", "get", "watch", "list", "update", "delete", "patch"]
- apiGroups: ["batch"]
  resources: ["jobs", "jobs/status"]
  verbs: ["create", "get", "watch", "list", "update", "delete", "patch"]
---
# cluster role to creating ML jobs in desired namespaces
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: job-creator
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "secrets"]
  verbs: ["create", "get", "watch", "list", "update", "delete", "patch"]
- apiGroups: ["batch"]
  resources: ["jobs", "jobs/status"]
  verbs: ["create", "get", "watch", "list", "update", "delete", "patch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wandb-launch-serviceaccount
  namespace: wandb
---
# role binding for namespaced role
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wandb-launch-role-binding
  namespace: wandb
subjects:
- kind: ServiceAccount
  name: wandb-launch-serviceaccount
  namespace: wandb
roleRef:
  kind: Role
  name: wandb-launch-agent
  apiGroup: rbac.authorization.k8s.io
---
# role binding to create ML jobs in another namespace (could use cluster role binding if we want to launch cluster wide)
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wandb-launch-cluster-role-binding
  namespace: default #TODO: SET YOUR TRAINING NAMESPACE
subjects:
- kind: ServiceAccount
  name: wandb-launch-serviceaccount
  namespace: wandb
roleRef:
  kind: ClusterRole
  name: job-creator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
data:
  launch-config.yaml: |
    base_url: https://api.wandb.ai # TODO: set wandb base url
    project: launch-welcome # TODO: set ml project
    max_jobs: -1 # TODO: set max concurrent jobs here
    registry:
      url: # TODO: set ecr repository url here
      ecr-provider: aws # TODO: set ecr provider here
      region: us-east-1 # TODO: specify registry region here
    build:
      type: kaniko
      cloud-provider: aws # TODO: set cloud provider here
      build-context-store: wandb-build # name here
    runner: # this can be set to specify default runner configuration
      type: sagemaker
      role_arn: # TODO: fill in sagemaker execution role
      s3_output_path: # TODO: set your sagemaker artifact output bucket

kind: ConfigMap
metadata:
  name: wandb-launch-configmap
  namespace: wandb
---
apiVersion: v1
kind: Secret
metadata:
  name: wandb-api-key
  namespace: wandb
type: kubernetes.io/basic-auth
stringData:
  password: ""  ### API KEY HERE
