# Generated by ariadne-codegen
# Source: tools/graphql_codegen/automations/

from __future__ import annotations

from typing import Optional

from wandb._pydantic import GQLResult

from .fragments import TriggerFields


class CreateAutomation(GQLResult):
    result: Optional[CreateAutomationResult]


class CreateAutomationResult(GQLResult):
    trigger: Optional[TriggerFields]


CreateAutomation.model_rebuild()
CreateAutomationResult.model_rebuild()
