# Generated by ariadne-codegen
# Source: tools/graphql_codegen/automations/

from __future__ import annotations

from wandb._pydantic import GQLResult


class DeleteAutomation(GQLResult):
    result: DeleteAutomationResult


class DeleteAutomationResult(GQLResult):
    success: bool


DeleteAutomation.model_rebuild()
