# Generated by ariadne-codegen
# Source: tools/graphql_codegen/automations/

from __future__ import annotations

from typing import Optional

from pydantic import Field

from wandb._pydantic import GQLBase

from .fragments import EnumInfo


class SupportedActionAndEventTypes(GQLBase):
    event_type_info: Optional[EnumInfo] = Field(alias="eventTypeInfo")
    action_type_info: Optional[EnumInfo] = Field(alias="actionTypeInfo")


SupportedActionAndEventTypes.model_rebuild()
