max_jobs: -1 # TODO: set the maximum number of concurrent jobs
base_url: https://api.wandb.ai # TODO: set api url
queues: # TODO: set to the names of your sagemaker queues
  - sagemaker
environment:
  type: aws
  region: us-east-2 # TODO: fill in aws region
registry:
  type: ecr
  repository: my-container-repository # TODO: fill in ecr repository name
builder:
  type: docker
