# Generated by ariadne-codegen
# Source: tools/graphql_codegen/artifacts/

from __future__ import annotations

from typing import List, Optional

from pydantic import Field

from wandb._pydantic import GQLBase


class ArtifactUsedBy(GQLBase):
    artifact: Optional[ArtifactUsedByArtifact]


class ArtifactUsedByArtifact(GQLBase):
    used_by: ArtifactUsedByArtifactUsedBy = Field(alias="usedBy")


class ArtifactUsedByArtifactUsedBy(GQLBase):
    edges: List[ArtifactUsedByArtifactUsedByEdges]


class ArtifactUsedByArtifactUsedByEdges(GQLBase):
    node: ArtifactUsedByArtifactUsedByEdgesNode


class ArtifactUsedByArtifactUsedByEdgesNode(GQLBase):
    name: str
    project: Optional[ArtifactUsedByArtifactUsedByEdgesNodeProject]


class ArtifactUsedByArtifactUsedByEdgesNodeProject(GQLBase):
    name: str
    entity_name: str = Field(alias="entityName")


ArtifactUsedBy.model_rebuild()
ArtifactUsedByArtifact.model_rebuild()
ArtifactUsedByArtifactUsedBy.model_rebuild()
ArtifactUsedByArtifactUsedByEdges.model_rebuild()
ArtifactUsedByArtifactUsedByEdgesNode.model_rebuild()
