# Generated by ariadne-codegen
# Source: tools/graphql_codegen/artifacts/

from __future__ import annotations

from typing import Literal

from pydantic import Field

from wandb._pydantic import GQLResult, Typename

from .fragments import ArtifactAliasFragment, PageInfoFragment


class ArtifactCollectionAliases(GQLResult):
    artifact_collection: ArtifactCollectionAliasesArtifactCollection | None = Field(
        validation_alias="artifactCollection", serialization_alias="artifactCollection"
    )


class ArtifactCollectionAliasesArtifactCollection(GQLResult):
    typename__: Typename[
        Literal["ArtifactCollection", "ArtifactPortfolio", "ArtifactSequence"]
    ]
    aliases: ArtifactCollectionAliasesArtifactCollectionAliases


class ArtifactCollectionAliasesArtifactCollectionAliases(GQLResult):
    page_info: PageInfoFragment = Field(
        validation_alias="pageInfo", serialization_alias="pageInfo"
    )
    edges: list[ArtifactCollectionAliasesArtifactCollectionAliasesEdges]


class ArtifactCollectionAliasesArtifactCollectionAliasesEdges(GQLResult):
    node: ArtifactAliasFragment | None


ArtifactCollectionAliases.model_rebuild()
ArtifactCollectionAliasesArtifactCollection.model_rebuild()
ArtifactCollectionAliasesArtifactCollectionAliases.model_rebuild()
ArtifactCollectionAliasesArtifactCollectionAliasesEdges.model_rebuild()
