# Generated by ariadne-codegen
# Source: tools/graphql_codegen/artifacts/

from __future__ import annotations

from typing import Optional

from pydantic import Field

from wandb._pydantic import GQLResult


class ArtifactType(GQLResult):
    project: Optional[ArtifactTypeProject]


class ArtifactTypeProject(GQLResult):
    artifact: Optional[ArtifactTypeProjectArtifact]


class ArtifactTypeProjectArtifact(GQLResult):
    artifact_type: ArtifactTypeProjectArtifactArtifactType = Field(alias="artifactType")


class ArtifactTypeProjectArtifactArtifactType(GQLResult):
    name: str


ArtifactType.model_rebuild()
ArtifactTypeProject.model_rebuild()
ArtifactTypeProjectArtifact.model_rebuild()
