# Generated by ariadne-codegen
# Source: tools/graphql_codegen/artifacts/

from __future__ import annotations

from typing import List, Optional

from pydantic import Field

from wandb._pydantic import GQLResult

from .fragments import FileFragment, PageInfoFragment


class ArtifactVersionFiles(GQLResult):
    project: Optional[ArtifactVersionFilesProject]


class ArtifactVersionFilesProject(GQLResult):
    artifact_type: Optional[ArtifactVersionFilesProjectArtifactType] = Field(
        alias="artifactType"
    )


class ArtifactVersionFilesProjectArtifactType(GQLResult):
    artifact: Optional[ArtifactVersionFilesProjectArtifactTypeArtifact]


class ArtifactVersionFilesProjectArtifactTypeArtifact(GQLResult):
    files: Optional[ArtifactVersionFilesProjectArtifactTypeArtifactFiles]


class ArtifactVersionFilesProjectArtifactTypeArtifactFiles(GQLResult):
    page_info: PageInfoFragment = Field(alias="pageInfo")
    edges: List[ArtifactVersionFilesProjectArtifactTypeArtifactFilesEdges]


class ArtifactVersionFilesProjectArtifactTypeArtifactFilesEdges(GQLResult):
    node: Optional[FileFragment]


ArtifactVersionFiles.model_rebuild()
ArtifactVersionFilesProject.model_rebuild()
ArtifactVersionFilesProjectArtifactType.model_rebuild()
ArtifactVersionFilesProjectArtifactTypeArtifact.model_rebuild()
ArtifactVersionFilesProjectArtifactTypeArtifactFiles.model_rebuild()
ArtifactVersionFilesProjectArtifactTypeArtifactFilesEdges.model_rebuild()
