# Generated by ariadne-codegen
# Source: tools/graphql_codegen/artifacts/

from __future__ import annotations

from typing import Literal, Optional

from pydantic import Field

from wandb._pydantic import GQLResult, Typename

from .fragments import FileUrlsFragment


class ArtifactCollectionMembershipFileUrls(GQLResult):
    project: Optional[ArtifactCollectionMembershipFileUrlsProject]


class ArtifactCollectionMembershipFileUrlsProject(GQLResult):
    artifact_collection: Optional[
        ArtifactCollectionMembershipFileUrlsProjectArtifactCollection
    ] = Field(alias="artifactCollection")


class ArtifactCollectionMembershipFileUrlsProjectArtifactCollection(GQLResult):
    typename__: Typename[
        Literal["ArtifactCollection", "ArtifactPortfolio", "ArtifactSequence"]
    ]
    artifact_membership: Optional[
        ArtifactCollectionMembershipFileUrlsProjectArtifactCollectionArtifactMembership
    ] = Field(alias="artifactMembership")


class ArtifactCollectionMembershipFileUrlsProjectArtifactCollectionArtifactMembership(
    GQLResult
):
    files: Optional[FileUrlsFragment]


ArtifactCollectionMembershipFileUrls.model_rebuild()
ArtifactCollectionMembershipFileUrlsProject.model_rebuild()
ArtifactCollectionMembershipFileUrlsProjectArtifactCollection.model_rebuild()
ArtifactCollectionMembershipFileUrlsProjectArtifactCollectionArtifactMembership.model_rebuild()
