# Generated by ariadne-codegen
# Source: tools/graphql_codegen/artifacts/

from __future__ import annotations

from typing import Optional

from pydantic import Field

from wandb._pydantic import GQLBase


class CreateRegistryMembers(GQLBase):
    create_project_members: Optional[CreateRegistryMembersCreateProjectMembers] = Field(
        alias="createProjectMembers"
    )


class CreateRegistryMembersCreateProjectMembers(GQLBase):
    success: bool


CreateRegistryMembers.model_rebuild()
