# Generated by ariadne-codegen
# Source: tools/graphql_codegen/artifacts/

from __future__ import annotations

from wandb._pydantic import GQLResult


class DeleteArtifactCollectionTags(GQLResult):
    result: DeleteArtifactCollectionTagsResult | None


class DeleteArtifactCollectionTagsResult(GQLResult):
    success: bool


DeleteArtifactCollectionTags.model_rebuild()
