# Generated by ariadne-codegen
# Source: tools/graphql_codegen/artifacts/

from __future__ import annotations

from typing import Optional

from pydantic import Field

from wandb._pydantic import GQLBase


class FetchArtifactManifest(GQLBase):
    project: Optional[FetchArtifactManifestProject]


class FetchArtifactManifestProject(GQLBase):
    artifact: Optional[FetchArtifactManifestProjectArtifact]


class FetchArtifactManifestProjectArtifact(GQLBase):
    current_manifest: Optional[FetchArtifactManifestProjectArtifactCurrentManifest] = (
        Field(alias="currentManifest")
    )


class FetchArtifactManifestProjectArtifactCurrentManifest(GQLBase):
    file: FetchArtifactManifestProjectArtifactCurrentManifestFile


class FetchArtifactManifestProjectArtifactCurrentManifestFile(GQLBase):
    direct_url: str = Field(alias="directUrl")


FetchArtifactManifest.model_rebuild()
FetchArtifactManifestProject.model_rebuild()
FetchArtifactManifestProjectArtifact.model_rebuild()
FetchArtifactManifestProjectArtifactCurrentManifest.model_rebuild()
