# Generated by ariadne-codegen
# Source: tools/graphql_codegen/artifacts/

from __future__ import annotations

from typing import List, Optional

from wandb._pydantic import GQLBase

from .fragments import OrgInfoFragment


class FetchOrgEntityFromEntity(GQLBase):
    entity: Optional[FetchOrgEntityFromEntityEntity]


class FetchOrgEntityFromEntityEntity(GQLBase):
    organization: Optional[OrgInfoFragment]
    user: Optional[FetchOrgEntityFromEntityEntityUser]


class FetchOrgEntityFromEntityEntityUser(GQLBase):
    organizations: List[OrgInfoFragment]


FetchOrgEntityFromEntity.model_rebuild()
FetchOrgEntityFromEntityEntity.model_rebuild()
FetchOrgEntityFromEntityEntityUser.model_rebuild()
