# Generated by ariadne-codegen
# Source: tools/graphql_codegen/artifacts/

from __future__ import annotations

from typing import Literal

from pydantic import Field

from wandb._pydantic import GQLResult, Typename

from .fragments import ArtifactAliasFragment, CollectionInfoFragment


class FetchLinkedArtifacts(GQLResult):
    artifact: FetchLinkedArtifactsArtifact | None


class FetchLinkedArtifactsArtifact(GQLResult):
    artifact_memberships: FetchLinkedArtifactsArtifactArtifactMemberships = Field(
        alias="artifactMemberships"
    )


class FetchLinkedArtifactsArtifactArtifactMemberships(GQLResult):
    edges: list[FetchLinkedArtifactsArtifactArtifactMembershipsEdges]


class FetchLinkedArtifactsArtifactArtifactMembershipsEdges(GQLResult):
    node: FetchLinkedArtifactsArtifactArtifactMembershipsEdgesNode | None


class FetchLinkedArtifactsArtifactArtifactMembershipsEdgesNode(GQLResult):
    version_index: int | None = Field(alias="versionIndex")
    aliases: list[ArtifactAliasFragment]
    artifact_collection: (
        FetchLinkedArtifactsArtifactArtifactMembershipsEdgesNodeArtifactCollection
        | None
    ) = Field(alias="artifactCollection")


class FetchLinkedArtifactsArtifactArtifactMembershipsEdgesNodeArtifactCollection(
    CollectionInfoFragment
):
    typename__: Typename[
        Literal["ArtifactCollection", "ArtifactPortfolio", "ArtifactSequence"]
    ]


FetchLinkedArtifacts.model_rebuild()
FetchLinkedArtifactsArtifact.model_rebuild()
FetchLinkedArtifactsArtifactArtifactMemberships.model_rebuild()
FetchLinkedArtifactsArtifactArtifactMembershipsEdges.model_rebuild()
FetchLinkedArtifactsArtifactArtifactMembershipsEdgesNode.model_rebuild()
