# Generated by ariadne-codegen
# Source: tools/graphql_codegen/artifacts/

from __future__ import annotations

from typing import Optional

from pydantic import Field

from wandb._pydantic import GQLResult

from .fragments import RegistriesPage


class FetchRegistries(GQLResult):
    organization: Optional[FetchRegistriesOrganization]


class FetchRegistriesOrganization(GQLResult):
    org_entity: Optional[FetchRegistriesOrganizationOrgEntity] = Field(
        alias="orgEntity"
    )


class FetchRegistriesOrganizationOrgEntity(GQLResult):
    name: str
    projects: Optional[RegistriesPage]


FetchRegistries.model_rebuild()
FetchRegistriesOrganization.model_rebuild()
FetchRegistriesOrganizationOrgEntity.model_rebuild()
