# Generated by ariadne-codegen
# Source: tools/graphql_codegen/artifacts/

from __future__ import annotations

from typing import Optional

from pydantic import Field

from wandb._pydantic import GQLResult

from .fragments import RegistryVersionsPage


class RegistryVersions(GQLResult):
    organization: Optional[RegistryVersionsOrganization]


class RegistryVersionsOrganization(GQLResult):
    org_entity: Optional[RegistryVersionsOrganizationOrgEntity] = Field(
        alias="orgEntity"
    )


class RegistryVersionsOrganizationOrgEntity(GQLResult):
    name: str
    artifact_memberships: Optional[RegistryVersionsPage] = Field(
        alias="artifactMemberships"
    )


RegistryVersions.model_rebuild()
RegistryVersionsOrganization.model_rebuild()
RegistryVersionsOrganizationOrgEntity.model_rebuild()
