# Generated by ariadne-codegen
# Source: tools/graphql_codegen/artifacts/

from __future__ import annotations

from typing import Optional

from pydantic import Field

from wandb._pydantic import GQLBase

from .fragments import RunInputArtifactConnectionFragment


class RunInputArtifacts(GQLBase):
    project: Optional[RunInputArtifactsProject]


class RunInputArtifactsProject(GQLBase):
    run: Optional[RunInputArtifactsProjectRun]


class RunInputArtifactsProjectRun(GQLBase):
    input_artifacts: Optional[RunInputArtifactConnectionFragment] = Field(
        alias="inputArtifacts"
    )


RunInputArtifacts.model_rebuild()
RunInputArtifactsProject.model_rebuild()
RunInputArtifactsProjectRun.model_rebuild()
