# Generated by ariadne-codegen
# Source: tools/graphql_codegen/artifacts/

from __future__ import annotations

from pydantic import Field

from wandb._pydantic import GQLResult

from .fragments import ArtifactFragment, PageInfoFragment


class RunInputArtifacts(GQLResult):
    project: RunInputArtifactsProject | None


class RunInputArtifactsProject(GQLResult):
    run: RunInputArtifactsProjectRun | None


class RunInputArtifactsProjectRun(GQLResult):
    artifacts: RunInputArtifactsProjectRunArtifacts | None


class RunInputArtifactsProjectRunArtifacts(GQLResult):
    total_count: int = Field(alias="totalCount")
    page_info: PageInfoFragment = Field(alias="pageInfo")
    edges: list[RunInputArtifactsProjectRunArtifactsEdges]


class RunInputArtifactsProjectRunArtifactsEdges(GQLResult):
    node: ArtifactFragment | None


RunInputArtifacts.model_rebuild()
RunInputArtifactsProject.model_rebuild()
RunInputArtifactsProjectRun.model_rebuild()
RunInputArtifactsProjectRunArtifacts.model_rebuild()
RunInputArtifactsProjectRunArtifactsEdges.model_rebuild()
