# Generated by ariadne-codegen
# Source: tools/graphql_codegen/artifacts/

from __future__ import annotations

from typing_extensions import Optional

from wandb._pydantic import GQLResult


class UnlinkArtifact(GQLResult):
    result: Optional[UnlinkArtifactResult]


class UnlinkArtifactResult(GQLResult):
    success: bool


UnlinkArtifact.model_rebuild()
