# Generated by ariadne-codegen
# Source: tools/graphql_codegen/artifacts/

from __future__ import annotations

from typing import Optional

from pydantic import Field

from wandb._pydantic import GQLResult

from .fragments import ArtifactFragment


class UpdateArtifact(GQLResult):
    update_artifact: Optional[UpdateArtifactUpdateArtifact] = Field(
        alias="updateArtifact"
    )


class UpdateArtifactUpdateArtifact(GQLResult):
    artifact: ArtifactFragment


UpdateArtifact.model_rebuild()
UpdateArtifactUpdateArtifact.model_rebuild()
