# Generated by ariadne-codegen
# Source: tools/graphql_codegen/artifacts/

from __future__ import annotations

from typing import Optional

from wandb._pydantic import GQLBase


class UpdateUserRegistryRole(GQLBase):
    result: Optional[UpdateUserRegistryRoleResult]


class UpdateUserRegistryRoleResult(GQLBase):
    success: bool


UpdateUserRegistryRole.model_rebuild()
