# Generated by ariadne-codegen
# Source: tools/graphql_codegen/artifacts/

from __future__ import annotations

from typing import Literal

from pydantic import Field

from wandb._pydantic import GQLResult, Typename

from .fragments import ArtifactCollectionFragment


class UpdateArtifactSequence(GQLResult):
    result: UpdateArtifactSequenceResult | None


class UpdateArtifactSequenceResult(GQLResult):
    artifact_collection: UpdateArtifactSequenceResultArtifactCollection = Field(
        alias="artifactCollection"
    )


class UpdateArtifactSequenceResultArtifactCollection(ArtifactCollectionFragment):
    typename__: Typename[
        Literal["ArtifactCollection", "ArtifactPortfolio", "ArtifactSequence"]
    ]


UpdateArtifactSequence.model_rebuild()
UpdateArtifactSequenceResult.model_rebuild()
