# Generated by ariadne-codegen
# Source: tools/graphql_codegen/artifacts/

from __future__ import annotations

from typing_extensions import Optional

from wandb._pydantic import GQLResult


class UpdateTeamRegistryRole(GQLResult):
    result: Optional[UpdateTeamRegistryRoleResult]


class UpdateTeamRegistryRoleResult(GQLResult):
    success: bool


UpdateTeamRegistryRole.model_rebuild()
