# Generated by ariadne-codegen

__all__ = [
    "DELETE_PROJECT_GQL",
    "FETCH_PROJECTS_GQL",
    "FETCH_PROJECT_GQL",
    "FETCH_REGISTRY_GQL",
    "RENAME_PROJECT_GQL",
    "UPSERT_REGISTRY_PROJECT_GQL",
    "FetchRegistry",
    "RenameProject",
    "UpsertRegistryProject",
    "DeleteProject",
    "FetchProjects",
    "FetchProject",
    "ArtifactTypeInput",
    "ProjectFragment",
    "RegistryFragment",
]
from .delete_project import DeleteProject
from .fetch_project import FetchProject
from .fetch_projects import FetchProjects
from .fetch_registry import FetchRegistry
from .fragments import ProjectFragment, RegistryFragment
from .input_types import ArtifactTypeInput
from .operations import (
    DELETE_PROJECT_GQL,
    FETCH_PROJECT_GQL,
    FETCH_PROJECTS_GQL,
    FETCH_REGISTRY_GQL,
    RENAME_PROJECT_GQL,
    UPSERT_REGISTRY_PROJECT_GQL,
)
from .rename_project import RenameProject
from .upsert_registry_project import UpsertRegistryProject
