---
name: 🐛 Client Bug - in the Python library
description: Create a report to help us improve W&B by reproducing and fixing bugs
title: "[CLI]: "
labels:
  - "cli"

body:
  - type: markdown
    attributes:
      value: |
        **Thanks :heart: for taking the time to fill out this bug report!**
        We kindly ask that you search to see if an issue [already exists](https://github.com/wandb/wandb/issues?q=is%3Aissue+sort%3Acreated-desc+) for the bug you encountered.

  - type: textarea
    attributes:
      label: Describe the bug
      description: |
        A clear and concise description of the issue you're experiencing.
        If relevant, add a minimal example to reproduce the error by running the code.
        If you observe an error, please paste the error message including the **full** traceback of the exception.

        Tip: For longer code you can also paste a link to a [GitHub Gist](https://gist.github.com).
      value: |
        <!--- Description of the issue below  -->

        <!--- A minimal code snippet between the quotes below  -->
        ```python

        ```

        <!--- A full traceback of the exception in the quotes below -->
        ```shell

        ```
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Files
      description: |
        Zip file with the run folder or any other artifacts that are helpful to reproduce the issue.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Environment
      description: |
        Information about your environment where you see the bug.

      value: |
        WandB version:

        OS:

        Python version:

        Versions of relevant libraries:

    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Context
      description: |
        Add any other context about the problem here.
    validations:
      required: false
