apiVersion: apps/v1
kind: Deployment
metadata:
  name: launch-agent
  namespace: wandb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: launch-agent
  template:
    metadata:
      labels:
        app: launch-agent
    spec:
      serviceAccountName: wandb-launch-serviceaccount
      containers:
      - name: launch-agent
        image: wandb/launch-agent-dev:1b2aa597
        resources:
          limits:
            memory: "2Gi"
            cpu: "1000m"
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop: ["ALL"]
          seccompProfile:
            type: RuntimeDefault
        env:
        - name: WANDB_PROJECT
          valueFrom:
            configMapKeyRef:
              name: wandb-setup
              key: wandb-project
        - name: WANDB_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: wandb-setup
              key: wandb-base-url
        - name: WANDB_LAUNCH_MAX_JOBS
          valueFrom:
            configMapKeyRef:
              name: wandb-setup
              key: wandb-agent-max-jobs
        - name: WANDB_API_KEY
          valueFrom:
            secretKeyRef:
              name: wandb-api-key
              key: password
