[package]
name = "wandb-xpu"
version = "0.7.1"
edition = "2024"
rust-version = "1.88"

[[bin]]
name = "build_proto"
path = "tools/build_proto.rs"

[dependencies]
log = "0.4.33"
env_logger = { version = "0.11.11", features = ["auto-color"] }
nvml-wrapper = "0.12.0"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
clap = { version = "4.6.5", features = ["derive"] }
sentry = { version = "0.49", default-features = false, features = [
    "backtrace",
    "contexts",
    "panic",
    "reqwest",
    "rustls",
] }
prost = "0.14.4"
prost-types = "0.14.4"
tonic = "0.14.6"
tonic-prost = "0.14.6"
tonic-reflection = "0.14.6"
tokio = { version = "1.53.1", features = ["full"] }
tokio-stream = "0.1.19"
chrono = "0.4.45"

tonic-prost-build = "0.14.6"
tempfile = "3.27.0"

libloading = "0.9"
async-trait = "0.1.91"
glob = "0.3.4"

[dev-dependencies]
zip = { version = "8.6.0", default-features = false, features = ["deflate"] }

[target.'cfg(not(all(target_family = "wasm", target_os = "unknown")))'.dependencies]
which = "8.0.5"

[target.'cfg(unix)'.dependencies]
nix = { version = "0.31.3", features = ["process"] }
core-foundation = "0.10.1"
libc = "0.2.189"
