# Generated by ariadne-codegen
# Source: tools/graphql_codegen/api/

from __future__ import annotations

from wandb._pydantic import GQLResult

from .fragments import UserInfoFragment


class CreateUserFromAdmin(GQLResult):
    result: CreateUserFromAdminResult | None


class CreateUserFromAdminResult(GQLResult):
    user: UserInfoFragment | None


CreateUserFromAdmin.model_rebuild()
CreateUserFromAdminResult.model_rebuild()
