# Generated by ariadne-codegen
# Source: tools/graphql_codegen/api/

from __future__ import annotations

from pydantic import Field

from wandb._pydantic import GQLId, GQLResult


class CreateTeam(GQLResult):
    result: CreateTeamResult | None


class CreateTeamResult(GQLResult):
    entity: CreateTeamResultEntity | None


class CreateTeamResultEntity(GQLResult):
    id: GQLId
    name: str
    available: bool | None
    photo_url: str | None = Field(alias="photoUrl")
    limits: str | None


CreateTeam.model_rebuild()
CreateTeamResult.model_rebuild()
