# Generated by ariadne-codegen
# Source: tools/graphql_codegen/api/

from __future__ import annotations

from typing import Optional

from pydantic import Field

from wandb._pydantic import GQLId, GQLResult

from .fragments import LightRunFragment, RunFragment


class GetRun(GQLResult):
    project: Optional[GetRunProject]


class GetRunProject(GQLResult):
    run: Optional[GetRunProjectRun]


class GetRunProjectRun(LightRunFragment, RunFragment):
    project_id: Optional[GQLId] = Field(alias="projectId", default=None)


GetRun.model_rebuild()
GetRunProject.model_rebuild()
