# Generated by ariadne-codegen
# Source: tools/graphql_codegen/api/

from __future__ import annotations

from typing import Optional

from wandb._pydantic import GQLResult

from .fragments import AgentFragment


class GetSweepAgent(GQLResult):
    project: Optional[GetSweepAgentProject]


class GetSweepAgentProject(GQLResult):
    sweep: Optional[GetSweepAgentProjectSweep]


class GetSweepAgentProjectSweep(GQLResult):
    agent: Optional[AgentFragment]


GetSweepAgent.model_rebuild()
GetSweepAgentProject.model_rebuild()
GetSweepAgentProjectSweep.model_rebuild()
