# Generated by ariadne-codegen
# Source: tools/graphql_codegen/api/

from __future__ import annotations

from typing_extensions import Optional

from wandb._pydantic import GQLResult

from .fragments import ProjectFragment


class GetProject(GQLResult):
    project: Optional[ProjectFragment]


GetProject.model_rebuild()
