# Generated by ariadne-codegen
# Source: tools/graphql_codegen/api/

from __future__ import annotations

from pydantic import Field

from wandb._pydantic import GQLResult

from .fragments import LightweightRunFragment, PageInfoFragment


class GetAgentRuns(GQLResult):
    project: GetAgentRunsProject | None


class GetAgentRunsProject(GQLResult):
    sweep: GetAgentRunsProjectSweep | None


class GetAgentRunsProjectSweep(GQLResult):
    agent: GetAgentRunsProjectSweepAgent | None


class GetAgentRunsProjectSweepAgent(GQLResult):
    runs: GetAgentRunsProjectSweepAgentRuns


class GetAgentRunsProjectSweepAgentRuns(GQLResult):
    page_info: PageInfoFragment = Field(alias="pageInfo")
    edges: list[GetAgentRunsProjectSweepAgentRunsEdges]


class GetAgentRunsProjectSweepAgentRunsEdges(GQLResult):
    cursor: str
    node: LightweightRunFragment


GetAgentRuns.model_rebuild()
GetAgentRunsProject.model_rebuild()
GetAgentRunsProjectSweep.model_rebuild()
GetAgentRunsProjectSweepAgent.model_rebuild()
GetAgentRunsProjectSweepAgentRuns.model_rebuild()
GetAgentRunsProjectSweepAgentRunsEdges.model_rebuild()
