version: "2"

run:
  timeout: 5m

formatters:
  enable:
    - gofmt
    - golines

linters:
  enable:
    - goimports
    - govet
    - gocritic
    - gocyclo
  exclusions:
    # https://golangci-lint.run/usage/false-positives/#preset-std-error-handling
    presets:
      - std-error-handling

linters-settings:
  gocyclo:
    min-complexity: 21
  goimports:
    local-prefixes: github.com/wandb/wandb
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance

issues:
  exclude-dirs:
    - vendor
  exclude-files:
    - "wire_gen\\.go$"
