# Generated by ariadne-codegen
# Source: tools/graphql_codegen/utils/

__all__ = ["FETCH_ORG_ENTITY_FROM_ORGANIZATION_GQL", "SERVER_FEATURES_QUERY_GQL"]

SERVER_FEATURES_QUERY_GQL = """
query ServerFeaturesQuery {
  serverInfo {
    features {
      name
      isEnabled
    }
  }
}
"""

FETCH_ORG_ENTITY_FROM_ORGANIZATION_GQL = """
query FetchOrgEntityFromOrganization($organization: String!) {
  organization(name: $organization) {
    orgEntity {
      name
    }
  }
}
"""
