	)
	require.NoError(t, err)

	msg, err := source.Read(100, 10*time.Second)
	require.NoError(t, err)
	require.NotNil(t, msg)
	assert.IsType(t, leet.ChunkedBatchMsg{}, msg)
	chunkedBatchMsg := msg.(leet.ChunkedBatchMsg)
	require.NotNil(t, chunkedBatchMsg.Msgs)
	assert.Len(t, chunkedBatchMsg.Msgs, 4)

	assert.IsType(t, leet.RunMsg{}, chunkedBatchMsg.Msgs[0])
	runMsg := chunkedBatchMsg.Msgs[0].(leet.RunMsg)
	assert.Equal(t, "run-id", runMsg.ID)
	assert.Equal(t, "project", runMsg.Project)
	assert.Equal(t, "run_display_name", runMsg.DisplayName)
	assert.Nil(t, runMsg.Config)

	assert.IsType(t, leet.SummaryMsg{}, chunkedBatchMsg.Msgs[1])
	summaryMsg := chunkedBatchMsg.Msgs[1].(leet.SummaryMsg)
	assert.NotNil(t, summaryMsg.Summary)
	assert.Len(t, summaryMsg.Summary, 1)
	assert.Equal(t, "loss", summaryMsg.Summary[0].Update[0].Key)
	assert.Equal(t, "0.6", summaryMsg.Summary[0].Update[0].ValueJson)

	assert.IsType(t, leet.HistoryMsg{}, chunkedBatchMsg.Msgs[2])
	historyMsg := chunkedBatchMsg.Msgs[2].(leet.HistoryMsg)
	assert.Contains(t, historyMsg.Metrics, "loss")
	assert.Equal(t, []float64{0, 1, 2}, historyMsg.Metrics["loss"].X)
	assert.Equal(t, []float64{1.0, 0.8, 0.6}, historyMsg.Metrics["loss"].Y)

	assert.IsType(t, leet.FileCompleteMsg{}, chunkedBatchMsg.Msgs[3])
	fileCompleteMsg := chunkedBatchMsg.Msgs[3].(leet.FileCompleteMsg)
	assert.Equal(t, int32(0), fileCompleteMsg.ExitCode)
}
