EXTERNAL_SENTRY_DSN_KEY = "EXTERNALKEY"
EXTERNAL_SENTRY_PROJECT = "123456"
INTERNAL_SENTRY_DSN_KEY = "INTERNALKEY"
INTERNAL_SENTRY_PROJECT = "654321"
API_SERVER_ADDRESS = "127.0.0.1:{port}"
SENTRY_DSN_FORMAT = "http://{key}@{address}/{project}"
WANDB_DSN_URL_FORMAT = SENTRY_DSN_FORMAT.format(
    key=INTERNAL_SENTRY_DSN_KEY,
    address=API_SERVER_ADDRESS,
    project=INTERNAL_SENTRY_PROJECT,
)
EXTERNAL_DSN_URL_FORMAT = SENTRY_DSN_FORMAT.format(
    key=EXTERNAL_SENTRY_DSN_KEY,
    address=API_SERVER_ADDRESS,
    project=EXTERNAL_SENTRY_PROJECT,
)
