apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
spec:
  restartPolicy: Never
  containers:
    - name: gpu-sdk
      image: gcr.io/wandb-client-cicd/gpu-sdk:latest
      env:
        - name: WANDB_API_KEY
          value: WANDB_API_KEY_PLACEHOLDER
  #    command: ["tail", "-f", "/dev/null"]
      # do not restart the container if it exits
      resources:
        limits:
          cpu: 1.999
          nvidia.com/gpu: 2
        requests:
          cpu: 1.5
  #    ports:
  #    - containerPort: 80
