[package]
name = "xtask"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
prost-build = "0.13"
tempfile.workspace = true

[lints]
workspace = true
