[package]
name = "leet-proto"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish.workspace = true

[dependencies]
prost.workspace = true
prost-types.workspace = true

[lints]
workspace = true
