mutation CreateDefaultResourceConfig(
    $entityName: String!
    $resource: String!
    $config: JSONString!
    $templateVariables: JSONString
) {
    createDefaultResourceConfig(
        input: {
            entityName: $entityName
            resource: $resource
            config: $config
            templateVariables: $templateVariables
        }
    ) {
        defaultResourceConfigID
        success
    }
}

mutation CreateRunQueue(
    $entity: String!
    $project: String!
    $queueName: String!
    $access: RunQueueAccessType!
    $prioritizationMode: RunQueuePrioritizationMode
    $defaultResourceConfigID: ID
) {
    createRunQueue(
        input: {
            entityName: $entity
            projectName: $project
            queueName: $queueName
            access: $access
            prioritizationMode: $prioritizationMode
            defaultResourceConfigID: $defaultResourceConfigID
        }
    ) {
        success
        queueID
    }
}

mutation UpsertRunQueue(
    $entityName: String!
    $projectName: String!
    $queueName: String!
    $resourceType: String!
    $resourceConfig: JSONString!
    $templateVariables: JSONString
    $prioritizationMode: RunQueuePrioritizationMode
    $externalLinks: JSONString
    $clientMutationId: String
) {
    upsertRunQueue(
        input: {
            entityName: $entityName
            projectName: $projectName
            queueName: $queueName
            resourceType: $resourceType
            resourceConfig: $resourceConfig
            templateVariables: $templateVariables
            prioritizationMode: $prioritizationMode
            externalLinks: $externalLinks
            clientMutationId: $clientMutationId
        }
    ) {
        success
        configSchemaValidationErrors
    }
}
