query QueryRunInfo(
    $entity: String!,
    $project: String!,
    $run: String!,
) {
    project(name: $project, entityName: $entity) {
        run(name: $run) {
            ...LeetRun
            # @genqlient(pointer: false)
            summaryMetrics
        }
    }
}

fragment LeetRun on Run {
    name
    # @genqlient(pointer: false)
    displayName
    # @genqlient(pointer: false)
    state
    # @genqlient(pointer: false)
    notes
    tags
    # @genqlient(pointer: false)
    config
}
