[package]
name = "leet-data"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish.workspace = true

[dependencies]
leet-proto.workspace = true
regex.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
proptest.workspace = true
tempfile.workspace = true

[lints]
workspace = true
