"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing
import typing_extensions
import wandb.proto.wandb_base_pb2

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class ServerShutdownRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    _INFO_FIELD_NUMBER: builtins.int

    @property
    def _info(self) -> wandb.proto.wandb_base_pb2._RecordInfo: ...

    def __init__(self,
        *,
        _info : typing.Optional[wandb.proto.wandb_base_pb2._RecordInfo] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"_info",b"_info"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"_info",b"_info"]) -> None: ...
global___ServerShutdownRequest = ServerShutdownRequest

class ServerShutdownResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...

    def __init__(self,
        ) -> None: ...
global___ServerShutdownResponse = ServerShutdownResponse

class ServerStatusRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    _INFO_FIELD_NUMBER: builtins.int

    @property
    def _info(self) -> wandb.proto.wandb_base_pb2._RecordInfo: ...

    def __init__(self,
        *,
        _info : typing.Optional[wandb.proto.wandb_base_pb2._RecordInfo] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"_info",b"_info"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"_info",b"_info"]) -> None: ...
global___ServerStatusRequest = ServerStatusRequest

class ServerStatusResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...

    def __init__(self,
        ) -> None: ...
global___ServerStatusResponse = ServerStatusResponse

class ServerInformInitRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    _INFO_FIELD_NUMBER: builtins.int

    @property
    def _info(self) -> wandb.proto.wandb_base_pb2._RecordInfo: ...

    def __init__(self,
        *,
        _info : typing.Optional[wandb.proto.wandb_base_pb2._RecordInfo] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"_info",b"_info"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"_info",b"_info"]) -> None: ...
global___ServerInformInitRequest = ServerInformInitRequest

class ServerInformInitResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...

    def __init__(self,
        ) -> None: ...
global___ServerInformInitResponse = ServerInformInitResponse

class ServerInformFinishRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    _INFO_FIELD_NUMBER: builtins.int

    @property
    def _info(self) -> wandb.proto.wandb_base_pb2._RecordInfo: ...

    def __init__(self,
        *,
        _info : typing.Optional[wandb.proto.wandb_base_pb2._RecordInfo] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"_info",b"_info"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"_info",b"_info"]) -> None: ...
global___ServerInformFinishRequest = ServerInformFinishRequest

class ServerInformFinishResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...

    def __init__(self,
        ) -> None: ...
global___ServerInformFinishResponse = ServerInformFinishResponse

class ServerInformTeardownRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    EXIT_CODE_FIELD_NUMBER: builtins.int
    _INFO_FIELD_NUMBER: builtins.int
    exit_code: builtins.int = ...

    @property
    def _info(self) -> wandb.proto.wandb_base_pb2._RecordInfo: ...

    def __init__(self,
        *,
        exit_code : builtins.int = ...,
        _info : typing.Optional[wandb.proto.wandb_base_pb2._RecordInfo] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"_info",b"_info"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"_info",b"_info",u"exit_code",b"exit_code"]) -> None: ...
global___ServerInformTeardownRequest = ServerInformTeardownRequest

class ServerInformTeardownResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...

    def __init__(self,
        ) -> None: ...
global___ServerInformTeardownResponse = ServerInformTeardownResponse
