#!/bin/bash
set -e

SRC="wandb/sdk/"
DEST="wandb/sdk_py27/"
DEST_TMP="wandb/sdk_py27_tmp/"

dest=$DEST
check=false

if [ "$1" == "--check" ]; then
	check=true
	dest=$DEST_TMP
fi

if [ "$dest" == "" -o "$dest" == "/" ]; then
	echo "SAFETY CHECK"
	exit 1
fi

mkdir -p $dest
rm -f ${dest}/*.py

cp -f $SRC/*.py $dest
python3 -m libcst.tool codemod --no-format remove_types.RemoveTypesTransformer $dest/*.py

for f in $dest/*.py; do
  sed -i.tmp 's/__COMMENT__/# /g; 1s/^#$/# File is generated by: tox -e codemod/' $f
  rm $f.tmp
  chmod -w $f
  b=`basename $f`
  cnt_src=`wc -l <$SRC/$b`
  cnt_dest=`wc -l <$dest/$b`
  if [ $cnt_src -ne $cnt_dest ]; then
  	echo "ERROR: mismatch file length $b $cnt_src != $cnt_dest"
  fi
done

if $check; then
	#diff -q $DEST $DEST_TMP | egrep "[.]py$"
	set +e
	diff --exclude="*.pyc" --exclude="__pycache__" -q $DEST $DEST_TMP
	result="$?"
	set -e
	rm ${dest}*
	rmdir $dest
	if [ $result -ne 0 ]; then
		echo "ERROR: codemod check failed."
		exit 1
	fi
fi
