apiVersion: v1
kind: Pod
metadata:
  name: cpu-pod
spec:
  restartPolicy: Never
  containers:
    - name: cpu-sdk
      image: gcr.io/wandb-client-cicd/cpu-sdk:latest
      env:
        - name: WANDB_API_KEY
          value: WANDB_API_KEY_PLACEHOLDER
      command: ["tail", "-f", "/dev/null"]
      resources:
        limits:
          cpu: 1.999
        requests:
          cpu: 1.0
