//! Port of `core/pkg/leveldb/crc.go` (a fork of golang/leveldb's `crc` package).
//!
//! The checksum algorithm used throughout leveldb.
//!
//! The algorithm is CRC-32 with Castagnoli's polynomial, followed by a bit
//! rotation and an additional delta. The additional processing is to lessen the
//! probability of arbitrary key/value data coincidentally containing bytes that
//! look like a checksum.
//!
//! To calculate the u32 checksum of some data:
//!
//! ```
//! let u: u32 = leet_wire::crc::Crc32c::new(b"data").value();
//! assert_ne!(u, 0);
//! ```
//!
//! In leveldb, the u32 value is then stored in little-endian format.

/// CRC algorithm selector.
///
/// Go: `CRCAlgo` with constants `CRCAlgoCustom` and `CRCAlgoIEEE`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum CrcAlgo {
    /// Go: `CRCAlgoCustom` — CRC-32C (Castagnoli) with leveldb's rotate+delta masking.
    #[default]
    Custom,
    /// Go: `CRCAlgoIEEE` — plain CRC-32 with the IEEE polynomial.
    Ieee,
}

/// A running CRC-32C (Castagnoli) checksum.
///
/// Go: `CRC32c`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct Crc32c(u32);

impl Crc32c {
    /// Go: `NewCRC32c`.
    pub fn new(b: &[u8]) -> Self {
        Crc32c(0).update(b)
    }

    /// Go: `CRC32c.Update`.
    ///
    /// `crc32c::crc32c_append` composes exactly like Go's `crc32.Update`
    /// (both handle the pre/post bit inversion internally).
    #[must_use]
    pub fn update(self, b: &[u8]) -> Self {
        Crc32c(crc32c::crc32c_append(self.0, b))
    }

    /// Go: `CRC32c.Value` — the rotate/mask scheme, verbatim:
    /// `uint32(c>>15|c<<17) + 0xa282ead8` (i.e. rotate right by 15, plus delta).
    pub fn value(self) -> u32 {
        self.0.rotate_right(15).wrapping_add(0xa282_ead8)
    }
}

/// Reflected IEEE CRC-32 table (Go: `crc32.MakeTable(crc32.IEEE)`).
///
/// Hand-rolled because the `crc32c` crate is Castagnoli-only; matches Go's
/// `hash/crc32` simple table algorithm bit-for-bit.
const TABLE_CRC32_IEEE: [u32; 256] = make_crc32_table(0xedb8_8320);

const fn make_crc32_table(poly: u32) -> [u32; 256] {
    let mut table = [0u32; 256];
    let mut i = 0;
    while i < 256 {
        let mut crc = i as u32;
        let mut j = 0;
        while j < 8 {
            crc = if crc & 1 == 1 {
                (crc >> 1) ^ poly
            } else {
                crc >> 1
            };
            j += 1;
        }
        table[i] = crc;
        i += 1;
    }
    table
}

/// Equivalent of Go's `crc32.Update(crc, tableCRC32ieee, b)`.
fn crc32_ieee_update(crc: u32, b: &[u8]) -> u32 {
    let mut crc = !crc;
    for &byte in b {
        crc = TABLE_CRC32_IEEE[((crc ^ byte as u32) & 0xff) as usize] ^ (crc >> 8);
    }
    !crc
}

/// Go: `CRCStandard` — plain IEEE CRC-32 checksum.
pub fn crc_standard(b: &[u8]) -> u32 {
    crc32_ieee_update(0, b)
}

/// Go: `CRCCustom` — masked CRC-32C checksum.
pub fn crc_custom(b: &[u8]) -> u32 {
    Crc32c::new(b).value()
}

impl From<Crc32c> for u32 {
    /// Raw (unmasked) CRC state, like Go's `uint32(c)` conversion.
    fn from(c: Crc32c) -> u32 {
        c.0
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // The Go package has no crc_test.go; these known-answer vectors were
    // generated by running the Go spec (core/pkg/leveldb) directly.
    #[test]
    fn test_go_oracle_vectors() {
        assert_eq!(crc_standard(b"123456789"), 0xcbf4_3926);
        assert_eq!(crc_custom(b"123456789"), 0xc78a_b0e5);
        assert_eq!(u32::from(Crc32c::new(b"123456789")), 0xe306_9283);
        assert_eq!(crc_custom(b""), 0xa282_ead8);
        assert_eq!(crc_standard(b""), 0x0000_0000);
        assert_eq!(crc_custom(&[0u8]), 0x4925_8fd2);
    }

    #[test]
    fn test_update_composes() {
        // Go: NewCRC32c("1234").Update("56789") == NewCRC32c("123456789").
        let c = Crc32c::new(b"1234").update(b"56789");
        assert_eq!(c, Crc32c::new(b"123456789"));
    }
}
