name: Validate that PR contains release notes

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  validate_release_notes:
    runs-on: ubuntu-latest
    steps:
      - name: Validate release notes
        uses: wandb/auto-release-notes@8264e54d996151cdd083dfd6914a757e8001f226
