name: Regenerate Python Requirements

on:
  # Allow manual runs.
  workflow_dispatch:

  # Run weekly on Monday at 9 or 10 AM Pacific time (17:00 UTC).
  schedule: [cron: "0 17 * * 1"]

jobs:
  regenerate-requirements:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6
        with:
          python-version: "3.13"

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Run requirements/generate.sh
        run: bash requirements/generate.sh --upgrade

      - name: Create pull request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8
        with:
          branch: regenerate-requirements
          delete-branch: true
          title: "chore: update Python requirements"
          body: >
            Applies updates from `requirements/generate.sh`.

            Please approve and merge if tests pass. If tests fail due to
            a dependency update, consider improving the tests or implementation.
            If CI fails because of a bug in a dependency, update
            `requirements/requirements_dev.txt` and rerun the action. Consider
            filing a bug for the dependency.

            If there are security or license issues in some upgraded packages,
            consider adding pins in `requirements/constraints.txt` and
            rerunning the action.
