name: Release Launch Agent

on:
  workflow_dispatch:
    inputs:
      preReleaseString:
        type: string
        description: The pre-release string for this release, leave empty for official releases
        default: ""
      candidateTag:
        type: string
        required: true
        description: The tag of the wandb/launch-agent-dev repo to be promoted

jobs:
  release-launch-agent:
    name: Launch Agent Release
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username:
          password:

      - name: Push to official repo
        run: |
          REPO=wandb/launch-agent
          IMAGE=wandb/launch-agent-dev:${{ github.event.inputs.candidateTag }}
          echo "Pulling image $IMAGE"
          docker pull $IMAGE

          # Get full tag
          SDK_RELEASE_VERSION=$(docker run --rm --entrypoint wandb $IMAGE --version | awk '{print $3}')

          if [[ $SDK_RELEASE_VERSION == *"dev"* ]]; then
            echo "selected image to be promoted is not based on a release"
            exit 1
          fi

          PRERELEASE_STRING=${{ github.event.inputs.preReleaseString }}
          length=${#PRERELEASE_STRING}
          isPrerelease=$((length > 0))
          if [ "$isPrerelease" -eq 1 ]
          then
            FULL_TAG="$SDK_RELEASE_VERSION-$PRERELEASE_STRING"
          else
            FULL_TAG=$SDK_RELEASE_VERSION
          fi

          echo "Tagging image $REPO:$FULL_TAG"
          docker tag $IMAGE $REPO:$FULL_TAG
          echo "Pushing image $REPO:$FULL_TAG"
          docker push $REPO:$FULL_TAG

          if [ "$isPrerelease" -eq 1 ]
          then
            echo "Tagging image $REPO:sdk-preview"
            docker tag $IMAGE $REPO:sdk-preview
            echo "Pushing image $REPO:sdk-preview"
            docker push $REPO:sdk-preview
          else
            echo "Tagging image $REPO:sdk"
            docker tag $IMAGE $REPO:sdk
            echo "Pushing image $REPO:sdk"
            docker push $REPO:sdk
          fi

          echo "Tagging image $REPO:latest"
          docker tag $IMAGE $REPO:latest
          echo "Pushing image $REPO:latest"
          docker push $REPO:latest
