name: Rust

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@4cda84d5c5c54efe2404f9d843567869ab1699d4 # stable
      - name: Setup python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6
        with:
          python-version: "3.11"
      - name: Install maturin
        run: pip install maturin
      - name: Activate python venv
        run: |
          python -m venv .venv
          source .venv/bin/activate
      - name: Build python package with maturin
        working-directory: ./experimental/client-rust
        run: maturin develop
      # - name: Build rust binary for testing
      #   working-directory: ./experimental/client-rust
      #   run: cargo build --verbose
      # - name: Run tests
      #   working-directory: ./experimental/client-rust
      #   run: cargo test --verbose
