name: SDK unit tests

on:
  workflow_call:
    inputs:
      python:
        type: string
        required: true
      runs-on:
        type: string
        required: true
      wheel-artifact:
        type: string
        required: true
      artifact-name:
        type: string
        required: true
      cluster-tests:
        type: boolean
        default: false

jobs:
  test:
    name: ${{ matrix.group }} of 4
    runs-on: ${{ inputs.cluster-tests && 'ubuntu-24.04' || inputs.runs-on }}
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        group: [1, 2, 3, 4]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - uses: ./.github/actions/run-nox-tests
        if: ${{ !inputs.cluster-tests }}
        with:
          python: ${{ inputs.python }}
          wheel-artifact: ${{ inputs.wheel-artifact }}
          test-group: ${{ matrix.group }}
          test-groups: "4"
          artifact-name: ${{ inputs.artifact-name }}-${{ matrix.group }}
      - uses: ./.github/actions/run-cluster-tests
        if: inputs.cluster-tests
        with:
          python: ${{ inputs.python }}
          session: unit_tests
          wheel-artifact: ${{ inputs.wheel-artifact }}
          test-group: ${{ matrix.group }}
          test-groups: "4"
          artifact-name: ${{ inputs.artifact-name }}-${{ matrix.group }}
          gcp-provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          gcp-service-account: ${{ secrets.GCP_REGISTRY_SA }}
